import { Word } from "@/types";

export const HSK_WORDS: Word[] = [
  // HSK 1
  { id: "ai", character: "爱", traditional: "愛", pinyin: "ài", meaning: "yêu; tình yêu", hskLevel: 1, examples: [{ chinese: "我爱你。", pinyin: "Wǒ ài nǐ.", vietnamese: "Tôi yêu bạn." }] },
  { id: "ba", character: "八", traditional: "八", pinyin: "bā", meaning: "tám (8)", hskLevel: 1, examples: [{ chinese: "八月。", pinyin: "Bā yuè.", vietnamese: "Tháng tám." }] },
  { id: "baba", character: "爸爸", traditional: "爸爸", pinyin: "bàba", meaning: "bố; cha", hskLevel: 1, examples: [{ chinese: "我爸爸很高。", pinyin: "Wǒ bàba hěn gāo.", vietnamese: "Bố tôi rất cao." }] },
  { id: "beizi", character: "杯子", traditional: "杯子", pinyin: "bēizi", meaning: "cái cốc; ly uống nước", hskLevel: 1, examples: [{ chinese: "这是我的杯子。", pinyin: "Zhè shì wǒ de bēizi.", vietnamese: "Đây là cốc của tôi." }] },
  { id: "beijing", character: "北京", traditional: "北京", pinyin: "Běijīng", meaning: "Bắc Kinh (thủ đô Trung Quốc)", hskLevel: 1, examples: [{ chinese: "我在北京工作。", pinyin: "Wǒ zài Běijīng gōngzuò.", vietnamese: "Tôi làm việc ở Bắc Kinh." }] },
  { id: "bu", character: "不", traditional: "不", pinyin: "bù", meaning: "không; chẳng", hskLevel: 1, examples: [{ chinese: "我不知道。", pinyin: "Wǒ bù zhīdào.", vietnamese: "Tôi không biết." }] },
  { id: "bukeqi", character: "不客气", traditional: "不客氣", pinyin: "bù kèqi", meaning: "không có gì (cảm ơn); đừng khách sáo", hskLevel: 1, examples: [{ chinese: "谢谢你！不客气！", pinyin: "Xièxie nǐ! Bù kèqi!", vietnamese: "Cảm ơn bạn! Không có gì!" }] },
  { id: "cai", character: "菜", traditional: "菜", pinyin: "cài", meaning: "rau; thức ăn; món ăn", hskLevel: 1, examples: [{ chinese: "这个菜很好吃。", pinyin: "Zhège cài hěn hǎochī.", vietnamese: "Món này rất ngon." }] },
  { id: "cha", character: "茶", traditional: "茶", pinyin: "chá", meaning: "trà; chè", hskLevel: 1, examples: [{ chinese: "你喝茶吗？", pinyin: "Nǐ hē chá ma?", vietnamese: "Bạn có uống trà không?" }] },
  { id: "chi", character: "吃", traditional: "吃", pinyin: "chī", meaning: "ăn", hskLevel: 1, examples: [{ chinese: "你吃了吗？", pinyin: "Nǐ chī le ma?", vietnamese: "Bạn ăn chưa?" }] },
  { id: "chuzuche", character: "出租车", traditional: "出租車", pinyin: "chūzūchē", meaning: "xe tắc xi", hskLevel: 1, examples: [{ chinese: "我坐出租车去机场。", pinyin: "Wǒ zuò chūzūchē qù jīchǎng.", vietnamese: "Tôi đi tắc xi đến sân bay." }] },
  { id: "da", character: "大", traditional: "大", pinyin: "dà", meaning: "to; lớn", hskLevel: 1, examples: [{ chinese: "这个城市很大。", pinyin: "Zhège chéngshì hěn dà.", vietnamese: "Thành phố này rất lớn." }] },
  { id: "de", character: "的", traditional: "的", pinyin: "de", meaning: "(trợ từ sở hữu)", hskLevel: 1, examples: [{ chinese: "我的书。", pinyin: "Wǒ de shū.", vietnamese: "Sách của tôi." }] },
  { id: "dian", character: "点", traditional: "點", pinyin: "diǎn", meaning: "giờ; điểm", hskLevel: 1, examples: [{ chinese: "现在几点？", pinyin: "Xiànzài jǐ diǎn?", vietnamese: "Bây giờ là mấy giờ?" }] },
  { id: "diannao", character: "电脑", traditional: "電腦", pinyin: "diànnǎo", meaning: "máy tính", hskLevel: 1, examples: [{ chinese: "我的电脑坏了。", pinyin: "Wǒ de diànnǎo huài le.", vietnamese: "Máy tính của tôi bị hỏng." }] },
  { id: "dianshi", character: "电视", traditional: "電視", pinyin: "diànshì", meaning: "tivi; truyền hình", hskLevel: 1, examples: [{ chinese: "我喜欢看电视。", pinyin: "Wǒ xǐhuān kàn diànshì.", vietnamese: "Tôi thích xem tivi." }] },
  { id: "dianying", character: "电影", traditional: "電影", pinyin: "diànyǐng", meaning: "phim điện ảnh", hskLevel: 1, examples: [{ chinese: "这部电影很好看。", pinyin: "Zhè bù diànyǐng hěn hǎokàn.", vietnamese: "Bộ phim này rất hay." }] },
  { id: "dongxi", character: "东西", traditional: "東西", pinyin: "dōngxi", meaning: "đồ vật; thứ; thứ gì đó", hskLevel: 1, examples: [{ chinese: "你买了什么东西？", pinyin: "Nǐ mǎi le shénme dōngxi?", vietnamese: "Bạn đã mua thứ gì?" }] },
  { id: "dou", character: "都", traditional: "都", pinyin: "dōu", meaning: "đều; tất cả", hskLevel: 1, examples: [{ chinese: "我们都是学生。", pinyin: "Wǒmen dōu shì xuésheng.", vietnamese: "Chúng tôi đều là học sinh." }] },
  { id: "du", character: "读", traditional: "讀", pinyin: "dú", meaning: "đọc", hskLevel: 1, examples: [{ chinese: "我在读书。", pinyin: "Wǒ zài dú shū.", vietnamese: "Tôi đang đọc sách." }] },
  { id: "duibuqi", character: "对不起", traditional: "對不起", pinyin: "duìbuqǐ", meaning: "xin lỗi", hskLevel: 1, examples: [{ chinese: "对不起，我来晚了。", pinyin: "Duìbuqǐ, wǒ lái wǎn le.", vietnamese: "Xin lỗi, tôi đến muộn." }] },
  { id: "duo", character: "多", traditional: "多", pinyin: "duō", meaning: "nhiều; lắm", hskLevel: 1, examples: [{ chinese: "这里人很多。", pinyin: "Zhèlǐ rén hěn duō.", vietnamese: "Nơi này rất nhiều người." }] },
  { id: "duoshao", character: "多少", traditional: "多少", pinyin: "duōshao", meaning: "bao nhiêu", hskLevel: 1, examples: [{ chinese: "这个多少钱？", pinyin: "Zhège duōshao qián?", vietnamese: "Cái này bao nhiêu tiền?" }] },
  { id: "erzi", character: "儿子", traditional: "兒子", pinyin: "érzi", meaning: "con trai", hskLevel: 1, examples: [{ chinese: "我有一个儿子。", pinyin: "Wǒ yǒu yī gè érzi.", vietnamese: "Tôi có một con trai." }] },
  { id: "er", character: "二", traditional: "二", pinyin: "èr", meaning: "hai (2)", hskLevel: 1, examples: [{ chinese: "二月。", pinyin: "Èr yuè.", vietnamese: "Tháng hai." }] },
  { id: "fandian", character: "饭店", traditional: "飯店", pinyin: "fàndiàn", meaning: "nhà hàng; khách sạn", hskLevel: 1, examples: [{ chinese: "我们去饭店吃饭吧。", pinyin: "Wǒmen qù fàndiàn chīfàn ba.", vietnamese: "Chúng ta đến nhà hàng ăn cơm nhé." }] },
  { id: "feiji", character: "飞机", traditional: "飛機", pinyin: "fēijī", meaning: "máy bay", hskLevel: 1, examples: [{ chinese: "我坐飞机去北京。", pinyin: "Wǒ zuò fēijī qù Běijīng.", vietnamese: "Tôi đi máy bay đến Bắc Kinh." }] },
  { id: "fenzhong", character: "分钟", traditional: "分鐘", pinyin: "fēnzhōng", meaning: "phút", hskLevel: 1, examples: [{ chinese: "再等五分钟。", pinyin: "Zài děng wǔ fēnzhōng.", vietnamese: "Chờ thêm năm phút nữa." }] },
  { id: "gaoxing", character: "高兴", traditional: "高興", pinyin: "gāoxìng", meaning: "vui vẻ; hạnh phúc", hskLevel: 1, examples: [{ chinese: "我很高兴认识你。", pinyin: "Wǒ hěn gāoxìng rènshi nǐ.", vietnamese: "Tôi rất vui được gặp bạn." }] },
  { id: "ge", character: "个", traditional: "個", pinyin: "gè", meaning: "(lượng từ)", hskLevel: 1, examples: [{ chinese: "一个苹果。", pinyin: "Yī gè píngguǒ.", vietnamese: "Một quả táo." }] },
  { id: "gongzuo", character: "工作", traditional: "工作", pinyin: "gōngzuò", meaning: "công việc; làm việc", hskLevel: 1, examples: [{ chinese: "你在哪儿工作？", pinyin: "Nǐ zài nǎr gōngzuò?", vietnamese: "Bạn làm việc ở đâu?" }] },
  { id: "gou", character: "狗", traditional: "狗", pinyin: "gǒu", meaning: "chó", hskLevel: 1, examples: [{ chinese: "我有一只狗。", pinyin: "Wǒ yǒu yī zhī gǒu.", vietnamese: "Tôi có một con chó." }] },
  { id: "hanyu", character: "汉语", traditional: "漢語", pinyin: "Hànyǔ", meaning: "tiếng Hán; tiếng Trung", hskLevel: 1, examples: [{ chinese: "我在学汉语。", pinyin: "Wǒ zài xué Hànyǔ.", vietnamese: "Tôi đang học tiếng Trung." }] },
  { id: "hao", character: "好", traditional: "好", pinyin: "hǎo", meaning: "tốt; hay; được", hskLevel: 1, examples: [{ chinese: "今天天气很好。", pinyin: "Jīntiān tiānqì hěn hǎo.", vietnamese: "Hôm nay thời tiết rất đẹp." }] },
  { id: "haochi", character: "好吃", traditional: "好吃", pinyin: "hǎochī", meaning: "ngon (thức ăn)", hskLevel: 1, examples: [{ chinese: "这个菜很好吃。", pinyin: "Zhège cài hěn hǎochī.", vietnamese: "Món này rất ngon." }] },
  { id: "hao2", character: "号", traditional: "號", pinyin: "hào", meaning: "số; ngày", hskLevel: 1, examples: [{ chinese: "今天几号？", pinyin: "Jīntiān jǐ hào?", vietnamese: "Hôm nay ngày mấy?" }] },
  { id: "he", character: "喝", traditional: "喝", pinyin: "hē", meaning: "uống", hskLevel: 1, examples: [{ chinese: "你喝什么？", pinyin: "Nǐ hē shénme?", vietnamese: "Bạn uống gì?" }] },
  { id: "he2", character: "和", traditional: "和", pinyin: "hé", meaning: "và; cùng", hskLevel: 1, examples: [{ chinese: "我和你一起去。", pinyin: "Wǒ hé nǐ yīqǐ qù.", vietnamese: "Tôi đi cùng với bạn." }] },
  { id: "hen", character: "很", traditional: "很", pinyin: "hěn", meaning: "rất; lắm", hskLevel: 1, examples: [{ chinese: "我很好。", pinyin: "Wǒ hěn hǎo.", vietnamese: "Tôi rất ổn." }] },
  { id: "houmian", character: "后面", traditional: "後面", pinyin: "hòumiàn", meaning: "phía sau; đằng sau", hskLevel: 1, examples: [{ chinese: "他在我后面。", pinyin: "Tā zài wǒ hòumiàn.", vietnamese: "Anh ấy ở phía sau tôi." }] },
  { id: "hui", character: "回", traditional: "回", pinyin: "huí", meaning: "quay lại; trở về", hskLevel: 1, examples: [{ chinese: "我明天回家。", pinyin: "Wǒ míngtiān huí jiā.", vietnamese: "Ngày mai tôi về nhà." }] },
  { id: "hui2", character: "会", traditional: "會", pinyin: "huì", meaning: "sẽ; biết làm; có thể", hskLevel: 1, examples: [{ chinese: "我会说汉语。", pinyin: "Wǒ huì shuō Hànyǔ.", vietnamese: "Tôi biết nói tiếng Trung." }] },
  { id: "ji", character: "几", traditional: "幾", pinyin: "jǐ", meaning: "mấy; bao nhiêu (dưới 10)", hskLevel: 1, examples: [{ chinese: "你几岁？", pinyin: "Nǐ jǐ suì?", vietnamese: "Bạn bao nhiêu tuổi?" }] },
  { id: "jia", character: "家", traditional: "家", pinyin: "jiā", meaning: "nhà; gia đình", hskLevel: 1, examples: [{ chinese: "我的家在北京。", pinyin: "Wǒ de jiā zài Běijīng.", vietnamese: "Nhà tôi ở Bắc Kinh." }] },
  { id: "jiao", character: "叫", traditional: "叫", pinyin: "jiào", meaning: "gọi là; tên là", hskLevel: 1, examples: [{ chinese: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", vietnamese: "Bạn tên là gì?" }] },
  { id: "jintian", character: "今天", traditional: "今天", pinyin: "jīntiān", meaning: "hôm nay", hskLevel: 1, examples: [{ chinese: "今天是周一。", pinyin: "Jīntiān shì Zhōuyī.", vietnamese: "Hôm nay là thứ Hai." }] },
  { id: "jiu", character: "九", traditional: "九", pinyin: "jiǔ", meaning: "chín (9)", hskLevel: 1, examples: [{ chinese: "九月。", pinyin: "Jiǔ yuè.", vietnamese: "Tháng chín." }] },
  { id: "kai", character: "开", traditional: "開", pinyin: "kāi", meaning: "mở; lái (xe)", hskLevel: 1, examples: [{ chinese: "请开门。", pinyin: "Qǐng kāi mén.", vietnamese: "Xin mở cửa." }] },
  { id: "kan", character: "看", traditional: "看", pinyin: "kàn", meaning: "xem; nhìn; đọc", hskLevel: 1, examples: [{ chinese: "我看书。", pinyin: "Wǒ kàn shū.", vietnamese: "Tôi đọc sách." }] },
  { id: "kuai", character: "块", traditional: "塊", pinyin: "kuài", meaning: "đồng (tiền tệ); mảnh", hskLevel: 1, examples: [{ chinese: "一块钱。", pinyin: "Yī kuài qián.", vietnamese: "Một đồng." }] },
  { id: "lai", character: "来", traditional: "來", pinyin: "lái", meaning: "đến; tới", hskLevel: 1, examples: [{ chinese: "请进来！", pinyin: "Qǐng jìn lái!", vietnamese: "Mời vào!" }] },
  { id: "laoshi", character: "老师", traditional: "老師", pinyin: "lǎoshī", meaning: "giáo viên; thầy cô", hskLevel: 1, examples: [{ chinese: "我的老师很好。", pinyin: "Wǒ de lǎoshī hěn hǎo.", vietnamese: "Thầy giáo tôi rất tốt." }] },
  { id: "le", character: "了", traditional: "了", pinyin: "le", meaning: "(trợ từ hoàn thành)", hskLevel: 1, examples: [{ chinese: "我吃了。", pinyin: "Wǒ chī le.", vietnamese: "Tôi đã ăn rồi." }] },
  { id: "leng", character: "冷", traditional: "冷", pinyin: "lěng", meaning: "lạnh", hskLevel: 1, examples: [{ chinese: "今天很冷。", pinyin: "Jīntiān hěn lěng.", vietnamese: "Hôm nay rất lạnh." }] },
  { id: "li", character: "里", traditional: "裡", pinyin: "lǐ", meaning: "trong; bên trong", hskLevel: 1, examples: [{ chinese: "包里有什么？", pinyin: "Bāo lǐ yǒu shénme?", vietnamese: "Trong túi có gì?" }] },
  { id: "liu", character: "六", traditional: "六", pinyin: "liù", meaning: "sáu (6)", hskLevel: 1, examples: [{ chinese: "六月。", pinyin: "Liù yuè.", vietnamese: "Tháng sáu." }] },
  { id: "mama", character: "妈妈", traditional: "媽媽", pinyin: "māma", meaning: "mẹ; má", hskLevel: 1, examples: [{ chinese: "我妈妈是老师。", pinyin: "Wǒ māma shì lǎoshī.", vietnamese: "Mẹ tôi là giáo viên." }] },
  { id: "meiguanxi", character: "没关系", traditional: "沒關係", pinyin: "méi guānxi", meaning: "không sao; không có gì", hskLevel: 1, examples: [{ chinese: "对不起！没关系。", pinyin: "Duìbuqǐ! Méi guānxi.", vietnamese: "Xin lỗi! Không sao." }] },
  { id: "meiyou", character: "没有", traditional: "沒有", pinyin: "méiyǒu", meaning: "không có; chưa", hskLevel: 1, examples: [{ chinese: "我没有钱。", pinyin: "Wǒ méiyǒu qián.", vietnamese: "Tôi không có tiền." }] },
  { id: "mifan", character: "米饭", traditional: "米飯", pinyin: "mǐfàn", meaning: "cơm", hskLevel: 1, examples: [{ chinese: "我喜欢吃米饭。", pinyin: "Wǒ xǐhuān chī mǐfàn.", vietnamese: "Tôi thích ăn cơm." }] },
  { id: "mingtian", character: "明天", traditional: "明天", pinyin: "míngtiān", meaning: "ngày mai", hskLevel: 1, examples: [{ chinese: "明天见！", pinyin: "Míngtiān jiàn!", vietnamese: "Hẹn gặp lại ngày mai!" }] },
  { id: "mingzi", character: "名字", traditional: "名字", pinyin: "míngzi", meaning: "tên", hskLevel: 1, examples: [{ chinese: "你的名字是什么？", pinyin: "Nǐ de míngzi shì shénme?", vietnamese: "Tên của bạn là gì?" }] },
  { id: "na", character: "哪", traditional: "哪", pinyin: "nǎ", meaning: "cái nào; nào", hskLevel: 1, examples: [{ chinese: "哪个是你的？", pinyin: "Nǎ gè shì nǐ de?", vietnamese: "Cái nào là của bạn?" }] },
  { id: "nar", character: "哪儿", traditional: "哪兒", pinyin: "nǎr", meaning: "ở đâu; nơi nào", hskLevel: 1, examples: [{ chinese: "你在哪儿？", pinyin: "Nǐ zài nǎr?", vietnamese: "Bạn đang ở đâu?" }] },
  { id: "na2", character: "那", traditional: "那", pinyin: "nà", meaning: "đó; kia; cái đó", hskLevel: 1, examples: [{ chinese: "那是什么？", pinyin: "Nà shì shénme?", vietnamese: "Đó là cái gì?" }] },
  { id: "neng", character: "能", traditional: "能", pinyin: "néng", meaning: "có thể; được", hskLevel: 1, examples: [{ chinese: "你能帮我吗？", pinyin: "Nǐ néng bāng wǒ ma?", vietnamese: "Bạn có thể giúp tôi không?" }] },
  { id: "ni", character: "你", traditional: "你", pinyin: "nǐ", meaning: "bạn; anh/chị (ngôi thứ 2)", hskLevel: 1, examples: [{ chinese: "你好！", pinyin: "Nǐ hǎo!", vietnamese: "Xin chào!" }] },
  { id: "nihao", character: "你好", traditional: "你好", pinyin: "nǐ hǎo", meaning: "xin chào", hskLevel: 1, examples: [{ chinese: "你好！你好吗？", pinyin: "Nǐ hǎo! Nǐ hǎo ma?", vietnamese: "Xin chào! Bạn có khỏe không?" }] },
  { id: "nian", character: "年", traditional: "年", pinyin: "nián", meaning: "năm", hskLevel: 1, examples: [{ chinese: "今年是哪年？", pinyin: "Jīnnián shì nǎ nián?", vietnamese: "Năm nay là năm nào?" }] },
  { id: "nver", character: "女儿", traditional: "女兒", pinyin: "nǚér", meaning: "con gái", hskLevel: 1, examples: [{ chinese: "我有一个女儿。", pinyin: "Wǒ yǒu yī gè nǚér.", vietnamese: "Tôi có một con gái." }] },
  { id: "pengyou", character: "朋友", traditional: "朋友", pinyin: "péngyou", meaning: "bạn bè; bạn", hskLevel: 1, examples: [{ chinese: "他是我的好朋友。", pinyin: "Tā shì wǒ de hǎo péngyou.", vietnamese: "Anh ấy là bạn tốt của tôi." }] },
  { id: "piaoliang", character: "漂亮", traditional: "漂亮", pinyin: "piàoliang", meaning: "đẹp; xinh xắn", hskLevel: 1, examples: [{ chinese: "你的衣服真漂亮！", pinyin: "Nǐ de yīfu zhēn piàoliang!", vietnamese: "Áo của bạn thật đẹp!" }] },
  { id: "pingguo", character: "苹果", traditional: "蘋果", pinyin: "píngguǒ", meaning: "quả táo", hskLevel: 1, examples: [{ chinese: "我喜欢吃苹果。", pinyin: "Wǒ xǐhuān chī píngguǒ.", vietnamese: "Tôi thích ăn táo." }] },
  { id: "qi", character: "七", traditional: "七", pinyin: "qī", meaning: "bảy (7)", hskLevel: 1, examples: [{ chinese: "七月。", pinyin: "Qī yuè.", vietnamese: "Tháng bảy." }] },
  { id: "qian", character: "钱", traditional: "錢", pinyin: "qián", meaning: "tiền", hskLevel: 1, examples: [{ chinese: "你有多少钱？", pinyin: "Nǐ yǒu duōshao qián?", vietnamese: "Bạn có bao nhiêu tiền?" }] },
  { id: "qianmian", character: "前面", traditional: "前面", pinyin: "qiánmiàn", meaning: "phía trước; đằng trước", hskLevel: 1, examples: [{ chinese: "前面是学校。", pinyin: "Qiánmiàn shì xuéxiào.", vietnamese: "Phía trước là trường học." }] },
  { id: "qing", character: "请", traditional: "請", pinyin: "qǐng", meaning: "xin mời; làm ơn", hskLevel: 1, examples: [{ chinese: "请坐！", pinyin: "Qǐng zuò!", vietnamese: "Mời ngồi!" }] },
  { id: "qu", character: "去", traditional: "去", pinyin: "qù", meaning: "đi; đến", hskLevel: 1, examples: [{ chinese: "我去学校。", pinyin: "Wǒ qù xuéxiào.", vietnamese: "Tôi đi trường học." }] },
  { id: "re", character: "热", traditional: "熱", pinyin: "rè", meaning: "nóng", hskLevel: 1, examples: [{ chinese: "今天很热。", pinyin: "Jīntiān hěn rè.", vietnamese: "Hôm nay rất nóng." }] },
  { id: "ren", character: "人", traditional: "人", pinyin: "rén", meaning: "người; con người", hskLevel: 1, examples: [{ chinese: "这里有很多人。", pinyin: "Zhèlǐ yǒu hěn duō rén.", vietnamese: "Nơi này có rất nhiều người." }] },
  { id: "renshi", character: "认识", traditional: "認識", pinyin: "rènshi", meaning: "quen biết; nhận ra", hskLevel: 1, examples: [{ chinese: "很高兴认识你！", pinyin: "Hěn gāoxìng rènshi nǐ!", vietnamese: "Rất vui được biết bạn!" }] },
  { id: "ri", character: "日", traditional: "日", pinyin: "rì", meaning: "ngày; mặt trời", hskLevel: 1, examples: [{ chinese: "一月一日。", pinyin: "Yī yuè yī rì.", vietnamese: "Ngày 1 tháng 1." }] },
  { id: "san", character: "三", traditional: "三", pinyin: "sān", meaning: "ba (3)", hskLevel: 1, examples: [{ chinese: "三月。", pinyin: "Sān yuè.", vietnamese: "Tháng ba." }] },
  { id: "shangdian", character: "商店", traditional: "商店", pinyin: "shāngdiàn", meaning: "cửa hàng; tiệm", hskLevel: 1, examples: [{ chinese: "商店几点开门？", pinyin: "Shāngdiàn jǐ diǎn kāimén?", vietnamese: "Cửa hàng mở cửa lúc mấy giờ?" }] },
  { id: "shang", character: "上", traditional: "上", pinyin: "shàng", meaning: "trên; phía trên; lên", hskLevel: 1, examples: [{ chinese: "书在桌子上。", pinyin: "Shū zài zhuōzi shàng.", vietnamese: "Sách ở trên bàn." }] },
  { id: "shangwu", character: "上午", traditional: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng (trước 12 giờ)", hskLevel: 1, examples: [{ chinese: "我上午有课。", pinyin: "Wǒ shàngwǔ yǒu kè.", vietnamese: "Buổi sáng tôi có lớp học." }] },
  { id: "shao", character: "少", traditional: "少", pinyin: "shǎo", meaning: "ít; thiếu", hskLevel: 1, examples: [{ chinese: "这里人很少。", pinyin: "Zhèlǐ rén hěn shǎo.", vietnamese: "Nơi này ít người." }] },
  { id: "shei", character: "谁", traditional: "誰", pinyin: "shéi", meaning: "ai; người nào", hskLevel: 1, examples: [{ chinese: "那是谁？", pinyin: "Nà shì shéi?", vietnamese: "Đó là ai?" }] },
  { id: "shenme", character: "什么", traditional: "什麼", pinyin: "shénme", meaning: "gì; cái gì; những gì", hskLevel: 1, examples: [{ chinese: "这是什么？", pinyin: "Zhè shì shénme?", vietnamese: "Đây là cái gì?" }] },
  { id: "shengri", character: "生日", traditional: "生日", pinyin: "shēngrì", meaning: "sinh nhật", hskLevel: 1, examples: [{ chinese: "今天是你的生日吗？", pinyin: "Jīntiān shì nǐ de shēngrì ma?", vietnamese: "Hôm nay là sinh nhật của bạn à?" }] },
  { id: "shi", character: "十", traditional: "十", pinyin: "shí", meaning: "mười (10)", hskLevel: 1, examples: [{ chinese: "十月。", pinyin: "Shí yuè.", vietnamese: "Tháng mười." }] },
  { id: "shihou", character: "时候", traditional: "時候", pinyin: "shíhou", meaning: "lúc; khi; thời điểm", hskLevel: 1, examples: [{ chinese: "什么时候出发？", pinyin: "Shénme shíhou chūfā?", vietnamese: "Khi nào khởi hành?" }] },
  { id: "shi2", character: "是", traditional: "是", pinyin: "shì", meaning: "là; đúng", hskLevel: 1, examples: [{ chinese: "我是学生。", pinyin: "Wǒ shì xuésheng.", vietnamese: "Tôi là học sinh." }] },
  { id: "shu", character: "书", traditional: "書", pinyin: "shū", meaning: "sách; quyển sách", hskLevel: 1, examples: [{ chinese: "我喜欢看书。", pinyin: "Wǒ xǐhuān kàn shū.", vietnamese: "Tôi thích đọc sách." }] },
  { id: "shui", character: "水", traditional: "水", pinyin: "shuǐ", meaning: "nước", hskLevel: 1, examples: [{ chinese: "请给我一杯水。", pinyin: "Qǐng gěi wǒ yī bēi shuǐ.", vietnamese: "Làm ơn cho tôi một ly nước." }] },
  { id: "shuiguo", character: "水果", traditional: "水果", pinyin: "shuǐguǒ", meaning: "hoa quả; trái cây", hskLevel: 1, examples: [{ chinese: "你喜欢吃什么水果？", pinyin: "Nǐ xǐhuān chī shénme shuǐguǒ?", vietnamese: "Bạn thích ăn loại trái cây gì?" }] },
  { id: "shuijiao", character: "睡觉", traditional: "睡覺", pinyin: "shuìjiào", meaning: "ngủ", hskLevel: 1, examples: [{ chinese: "我困了，想睡觉。", pinyin: "Wǒ kùn le, xiǎng shuìjiào.", vietnamese: "Tôi buồn ngủ, muốn ngủ." }] },
  { id: "shuo", character: "说", traditional: "說", pinyin: "shuō", meaning: "nói; kể", hskLevel: 1, examples: [{ chinese: "他说汉语。", pinyin: "Tā shuō Hànyǔ.", vietnamese: "Anh ấy nói tiếng Trung." }] },
  { id: "si", character: "四", traditional: "四", pinyin: "sì", meaning: "bốn (4)", hskLevel: 1, examples: [{ chinese: "四月。", pinyin: "Sì yuè.", vietnamese: "Tháng tư." }] },
  { id: "sui", character: "岁", traditional: "歲", pinyin: "suì", meaning: "tuổi", hskLevel: 1, examples: [{ chinese: "我二十岁。", pinyin: "Wǒ èrshí suì.", vietnamese: "Tôi hai mươi tuổi." }] },
  { id: "ta", character: "他", traditional: "他", pinyin: "tā", meaning: "anh ấy; ông ấy (ngôi thứ 3 nam)", hskLevel: 1, examples: [{ chinese: "他是我的朋友。", pinyin: "Tā shì wǒ de péngyou.", vietnamese: "Anh ấy là bạn của tôi." }] },
  { id: "ta2", character: "她", traditional: "她", pinyin: "tā", meaning: "cô ấy; bà ấy (ngôi thứ 3 nữ)", hskLevel: 1, examples: [{ chinese: "她很漂亮。", pinyin: "Tā hěn piàoliang.", vietnamese: "Cô ấy rất đẹp." }] },
  { id: "tai", character: "太", traditional: "太", pinyin: "tài", meaning: "quá; quá mức", hskLevel: 1, examples: [{ chinese: "这个太贵了！", pinyin: "Zhège tài guì le!", vietnamese: "Cái này quá đắt!" }] },
  { id: "tianqi", character: "天气", traditional: "天氣", pinyin: "tiānqì", meaning: "thời tiết", hskLevel: 1, examples: [{ chinese: "今天天气怎么样？", pinyin: "Jīntiān tiānqì zěnmeyàng?", vietnamese: "Hôm nay thời tiết thế nào?" }] },
  { id: "ting", character: "听", traditional: "聽", pinyin: "tīng", meaning: "nghe", hskLevel: 1, examples: [{ chinese: "我听音乐。", pinyin: "Wǒ tīng yīnyuè.", vietnamese: "Tôi nghe nhạc." }] },
  { id: "tongxue", character: "同学", traditional: "同學", pinyin: "tóngxué", meaning: "bạn học; bạn cùng lớp", hskLevel: 1, examples: [{ chinese: "他是我的同学。", pinyin: "Tā shì wǒ de tóngxué.", vietnamese: "Anh ấy là bạn học của tôi." }] },
  { id: "wo", character: "我", traditional: "我", pinyin: "wǒ", meaning: "tôi; tao (ngôi thứ 1)", hskLevel: 1, examples: [{ chinese: "我是越南人。", pinyin: "Wǒ shì Yuènán rén.", vietnamese: "Tôi là người Việt Nam." }] },
  { id: "women", character: "我们", traditional: "我們", pinyin: "wǒmen", meaning: "chúng tôi; chúng ta", hskLevel: 1, examples: [{ chinese: "我们是好朋友。", pinyin: "Wǒmen shì hǎo péngyou.", vietnamese: "Chúng tôi là bạn tốt." }] },
  { id: "wu", character: "五", traditional: "五", pinyin: "wǔ", meaning: "năm (5)", hskLevel: 1, examples: [{ chinese: "五月。", pinyin: "Wǔ yuè.", vietnamese: "Tháng năm." }] },
  { id: "xia", character: "下", traditional: "下", pinyin: "xià", meaning: "dưới; phía dưới; xuống", hskLevel: 1, examples: [{ chinese: "桌子下有什么？", pinyin: "Zhuōzi xià yǒu shénme?", vietnamese: "Dưới bàn có gì?" }] },
  { id: "xiawu", character: "下午", traditional: "下午", pinyin: "xiàwǔ", meaning: "buổi chiều (sau 12 giờ)", hskLevel: 1, examples: [{ chinese: "下午我有空。", pinyin: "Xiàwǔ wǒ yǒu kòng.", vietnamese: "Chiều tôi rảnh." }] },
  { id: "xiansheng", character: "先生", traditional: "先生", pinyin: "xiānsheng", meaning: "ông; thầy; chồng", hskLevel: 1, examples: [{ chinese: "李先生，你好！", pinyin: "Lǐ xiānsheng, nǐ hǎo!", vietnamese: "Xin chào ông Lý!" }] },
  { id: "xianzai", character: "现在", traditional: "現在", pinyin: "xiànzài", meaning: "bây giờ; hiện tại", hskLevel: 1, examples: [{ chinese: "现在几点了？", pinyin: "Xiànzài jǐ diǎn le?", vietnamese: "Bây giờ là mấy giờ rồi?" }] },
  { id: "xiang", character: "想", traditional: "想", pinyin: "xiǎng", meaning: "muốn; nghĩ; nhớ", hskLevel: 1, examples: [{ chinese: "我想学汉语。", pinyin: "Wǒ xiǎng xué Hànyǔ.", vietnamese: "Tôi muốn học tiếng Trung." }] },
  { id: "xiao", character: "小", traditional: "小", pinyin: "xiǎo", meaning: "nhỏ; bé", hskLevel: 1, examples: [{ chinese: "我有一只小猫。", pinyin: "Wǒ yǒu yī zhī xiǎo māo.", vietnamese: "Tôi có một con mèo nhỏ." }] },
  { id: "xie", character: "写", traditional: "寫", pinyin: "xiě", meaning: "viết", hskLevel: 1, examples: [{ chinese: "请写下你的名字。", pinyin: "Qǐng xiě xià nǐ de míngzi.", vietnamese: "Xin hãy viết tên của bạn xuống." }] },
  { id: "xie2", character: "谢谢", traditional: "謝謝", pinyin: "xièxie", meaning: "cảm ơn", hskLevel: 1, examples: [{ chinese: "谢谢你的帮助！", pinyin: "Xièxie nǐ de bāngzhù!", vietnamese: "Cảm ơn sự giúp đỡ của bạn!" }] },
  { id: "xingqi", character: "星期", traditional: "星期", pinyin: "xīngqī", meaning: "tuần; thứ (trong tuần)", hskLevel: 1, examples: [{ chinese: "今天星期几？", pinyin: "Jīntiān xīngqī jǐ?", vietnamese: "Hôm nay là thứ mấy?" }] },
  { id: "xuesheng", character: "学生", traditional: "學生", pinyin: "xuésheng", meaning: "học sinh; sinh viên", hskLevel: 1, examples: [{ chinese: "我是大学生。", pinyin: "Wǒ shì dàxuéshēng.", vietnamese: "Tôi là sinh viên đại học." }] },
  { id: "xuexi", character: "学习", traditional: "學習", pinyin: "xuéxí", meaning: "học tập; học", hskLevel: 1, examples: [{ chinese: "我每天学习汉语。", pinyin: "Wǒ měitiān xuéxí Hànyǔ.", vietnamese: "Mỗi ngày tôi học tiếng Trung." }] },
  { id: "xuexiao", character: "学校", traditional: "學校", pinyin: "xuéxiào", meaning: "trường học", hskLevel: 1, examples: [{ chinese: "我的学校很大。", pinyin: "Wǒ de xuéxiào hěn dà.", vietnamese: "Trường học của tôi rất lớn." }] },
  { id: "yi", character: "一", traditional: "一", pinyin: "yī", meaning: "một (1)", hskLevel: 1, examples: [{ chinese: "一月。", pinyin: "Yī yuè.", vietnamese: "Tháng một." }] },
  { id: "yifu", character: "衣服", traditional: "衣服", pinyin: "yīfu", meaning: "quần áo; trang phục", hskLevel: 1, examples: [{ chinese: "这件衣服很好看。", pinyin: "Zhè jiàn yīfu hěn hǎokàn.", vietnamese: "Bộ quần áo này rất đẹp." }] },
  { id: "yisheng", character: "医生", traditional: "醫生", pinyin: "yīshēng", meaning: "bác sĩ", hskLevel: 1, examples: [{ chinese: "我的朋友是医生。", pinyin: "Wǒ de péngyou shì yīshēng.", vietnamese: "Bạn của tôi là bác sĩ." }] },
  { id: "yiyuan", character: "医院", traditional: "醫院", pinyin: "yīyuàn", meaning: "bệnh viện", hskLevel: 1, examples: [{ chinese: "医院在哪儿？", pinyin: "Yīyuàn zài nǎr?", vietnamese: "Bệnh viện ở đâu?" }] },
  { id: "yizi", character: "椅子", traditional: "椅子", pinyin: "yǐzi", meaning: "ghế", hskLevel: 1, examples: [{ chinese: "请坐椅子。", pinyin: "Qǐng zuò yǐzi.", vietnamese: "Mời ngồi ghế." }] },
  { id: "you", character: "有", traditional: "有", pinyin: "yǒu", meaning: "có; tồn tại", hskLevel: 1, examples: [{ chinese: "我有一个哥哥。", pinyin: "Wǒ yǒu yī gè gēgē.", vietnamese: "Tôi có một người anh trai." }] },
  { id: "yue", character: "月", traditional: "月", pinyin: "yuè", meaning: "tháng; mặt trăng", hskLevel: 1, examples: [{ chinese: "一年有十二个月。", pinyin: "Yī nián yǒu shíèr gè yuè.", vietnamese: "Một năm có mười hai tháng." }] },
  { id: "zai", character: "在", traditional: "在", pinyin: "zài", meaning: "ở; tại; đang", hskLevel: 1, examples: [{ chinese: "我在中国。", pinyin: "Wǒ zài Zhōngguó.", vietnamese: "Tôi đang ở Trung Quốc." }] },
  { id: "zaijian", character: "再见", traditional: "再見", pinyin: "zàijiàn", meaning: "tạm biệt", hskLevel: 1, examples: [{ chinese: "再见！明天见！", pinyin: "Zàijiàn! Míngtiān jiàn!", vietnamese: "Tạm biệt! Hẹn gặp lại ngày mai!" }] },
  { id: "zenme", character: "怎么", traditional: "怎麼", pinyin: "zěnme", meaning: "như thế nào; làm thế nào", hskLevel: 1, examples: [{ chinese: "这个字怎么念？", pinyin: "Zhège zì zěnme niàn?", vietnamese: "Chữ này đọc thế nào?" }] },
  { id: "zenmeyang", character: "怎么样", traditional: "怎麼樣", pinyin: "zěnmeyàng", meaning: "thế nào; ra sao", hskLevel: 1, examples: [{ chinese: "你怎么样？", pinyin: "Nǐ zěnmeyàng?", vietnamese: "Bạn thế nào?" }] },
  { id: "zhe", character: "这", traditional: "這", pinyin: "zhè", meaning: "đây; này; cái này", hskLevel: 1, examples: [{ chinese: "这是什么？", pinyin: "Zhè shì shénme?", vietnamese: "Đây là cái gì?" }] },
  { id: "zhongguo", character: "中国", traditional: "中國", pinyin: "Zhōngguó", meaning: "Trung Quốc", hskLevel: 1, examples: [{ chinese: "我想去中国旅游。", pinyin: "Wǒ xiǎng qù Zhōngguó lǚyóu.", vietnamese: "Tôi muốn đi du lịch Trung Quốc." }] },
  { id: "zhongwu", character: "中午", traditional: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa; giữa trưa", hskLevel: 1, examples: [{ chinese: "中午我们一起吃饭吧。", pinyin: "Zhōngwǔ wǒmen yīqǐ chīfàn ba.", vietnamese: "Buổi trưa chúng ta ăn cơm cùng nhau nhé." }] },
  { id: "zhu", character: "住", traditional: "住", pinyin: "zhù", meaning: "sống; ở; cư trú", hskLevel: 1, examples: [{ chinese: "你住在哪儿？", pinyin: "Nǐ zhù zài nǎr?", vietnamese: "Bạn sống ở đâu?" }] },
  { id: "zhuozi", character: "桌子", traditional: "桌子", pinyin: "zhuōzi", meaning: "cái bàn", hskLevel: 1, examples: [{ chinese: "书在桌子上。", pinyin: "Shū zài zhuōzi shàng.", vietnamese: "Sách trên bàn." }] },
  { id: "zi", character: "字", traditional: "字", pinyin: "zì", meaning: "chữ; ký tự", hskLevel: 1, examples: [{ chinese: "这个字怎么写？", pinyin: "Zhège zì zěnme xiě?", vietnamese: "Chữ này viết thế nào?" }] },
  { id: "zuotian", character: "昨天", traditional: "昨天", pinyin: "zuótiān", meaning: "hôm qua", hskLevel: 1, examples: [{ chinese: "昨天你在哪儿？", pinyin: "Zuótiān nǐ zài nǎr?", vietnamese: "Hôm qua bạn ở đâu?" }] },
  { id: "zuo", character: "坐", traditional: "坐", pinyin: "zuò", meaning: "ngồi; ngồi (phương tiện)", hskLevel: 1, examples: [{ chinese: "请坐！", pinyin: "Qǐng zuò!", vietnamese: "Mời ngồi!" }] },
  { id: "zuo2", character: "做", traditional: "做", pinyin: "zuò", meaning: "làm; thực hiện", hskLevel: 1, examples: [{ chinese: "你在做什么？", pinyin: "Nǐ zài zuò shénme?", vietnamese: "Bạn đang làm gì?" }] },

  // HSK 2
  { id: "ba2", character: "吧", traditional: "吧", pinyin: "ba", meaning: "(trợ từ đề xuất/xác nhận)", hskLevel: 2, examples: [{ chinese: "我们走吧！", pinyin: "Wǒmen zǒu ba!", vietnamese: "Chúng ta đi thôi!" }] },
  { id: "bai", character: "白", traditional: "白", pinyin: "bái", meaning: "trắng; màu trắng", hskLevel: 2, examples: [] },
  { id: "ban", character: "班", traditional: "班", pinyin: "bān", meaning: "lớp học; ca (làm việc)", hskLevel: 2, examples: [] },
  { id: "bang", character: "帮助", traditional: "幫助", pinyin: "bāngzhù", meaning: "giúp đỡ", hskLevel: 2, examples: [{ chinese: "谢谢你的帮助。", pinyin: "Xièxie nǐ de bāngzhù.", vietnamese: "Cảm ơn sự giúp đỡ của bạn." }] },
  { id: "bao", character: "报纸", traditional: "報紙", pinyin: "bàozhǐ", meaning: "báo (giấy); tờ báo", hskLevel: 2, examples: [] },
  { id: "bi", character: "比", traditional: "比", pinyin: "bǐ", meaning: "so sánh; hơn", hskLevel: 2, examples: [{ chinese: "他比我高。", pinyin: "Tā bǐ wǒ gāo.", vietnamese: "Anh ấy cao hơn tôi." }] },
  { id: "bie", character: "别", traditional: "別", pinyin: "bié", meaning: "đừng; khác", hskLevel: 2, examples: [] },
  { id: "bingdan", character: "病", traditional: "病", pinyin: "bìng", meaning: "bệnh; ốm", hskLevel: 2, examples: [] },
  { id: "cai2", character: "才", traditional: "才", pinyin: "cái", meaning: "mới; chỉ vừa mới", hskLevel: 2, examples: [] },
  { id: "chuqu", character: "出", traditional: "出", pinyin: "chū", meaning: "ra; xuất", hskLevel: 2, examples: [] },
  { id: "chuqu2", character: "穿", traditional: "穿", pinyin: "chuān", meaning: "mặc; đi (giày)", hskLevel: 2, examples: [] },
  { id: "daan", character: "打", traditional: "打", pinyin: "dǎ", meaning: "đánh; gọi (điện thoại)", hskLevel: 2, examples: [] },
  { id: "dajia", character: "大家", traditional: "大家", pinyin: "dàjiā", meaning: "mọi người; tất cả mọi người", hskLevel: 2, examples: [] },
  { id: "dao", character: "到", traditional: "到", pinyin: "dào", meaning: "đến; tới nơi", hskLevel: 2, examples: [] },
  { id: "dei", character: "得", traditional: "得", pinyin: "de/dé/děi", meaning: "được; phải (cần phải)", hskLevel: 2, examples: [] },
  { id: "dengjia", character: "等", traditional: "等", pinyin: "děng", meaning: "đợi; chờ", hskLevel: 2, examples: [] },
  { id: "dianhua", character: "电话", traditional: "電話", pinyin: "diànhuà", meaning: "điện thoại", hskLevel: 2, examples: [] },
  { id: "dong", character: "懂", traditional: "懂", pinyin: "dǒng", meaning: "hiểu; biết", hskLevel: 2, examples: [] },
  { id: "duanliann", character: "锻炼", traditional: "鍛煉", pinyin: "duànliàn", meaning: "tập thể dục; rèn luyện", hskLevel: 2, examples: [] },
  { id: "fang", character: "房间", traditional: "房間", pinyin: "fángjiān", meaning: "phòng; căn phòng", hskLevel: 2, examples: [] },
  { id: "fei", character: "非常", traditional: "非常", pinyin: "fēicháng", meaning: "rất; vô cùng; cực kỳ", hskLevel: 2, examples: [] },
  { id: "fen", character: "分", traditional: "分", pinyin: "fēn", meaning: "điểm; phút; phần", hskLevel: 2, examples: [] },
  { id: "fu", character: "服务员", traditional: "服務員", pinyin: "fúwùyuán", meaning: "nhân viên phục vụ; bồi bàn", hskLevel: 2, examples: [] },
  { id: "gao", character: "高", traditional: "高", pinyin: "gāo", meaning: "cao; giỏi", hskLevel: 2, examples: [] },
  { id: "ge2", character: "哥哥", traditional: "哥哥", pinyin: "gēgē", meaning: "anh trai", hskLevel: 2, examples: [] },
  { id: "gei", character: "给", traditional: "給", pinyin: "gěi", meaning: "cho; đưa cho", hskLevel: 2, examples: [] },
  { id: "guo", character: "过", traditional: "過", pinyin: "guò", meaning: "qua; trải qua; (trợ từ kinh nghiệm)", hskLevel: 2, examples: [] },
  { id: "hao3", character: "还", traditional: "還", pinyin: "hái", meaning: "vẫn; còn; cũng", hskLevel: 2, examples: [] },
  { id: "hao4", character: "好看", traditional: "好看", pinyin: "hǎokàn", meaning: "đẹp; dễ nhìn", hskLevel: 2, examples: [] },
  { id: "he3", character: "黑", traditional: "黑", pinyin: "hēi", meaning: "đen; màu đen", hskLevel: 2, examples: [] },
  { id: "hong", character: "红", traditional: "紅", pinyin: "hóng", meaning: "đỏ; màu đỏ", hskLevel: 2, examples: [] },
  { id: "hua", character: "花", traditional: "花", pinyin: "huā", meaning: "hoa; tiêu (tiền)", hskLevel: 2, examples: [] },
  { id: "huanying", character: "欢迎", traditional: "歡迎", pinyin: "huānyíng", meaning: "chào mừng; hoan nghênh", hskLevel: 2, examples: [] },
  { id: "huihua", character: "回答", traditional: "回答", pinyin: "huídá", meaning: "trả lời; đáp lại", hskLevel: 2, examples: [] },
  { id: "ji2", character: "机场", traditional: "機場", pinyin: "jīchǎng", meaning: "sân bay", hskLevel: 2, examples: [] },
  { id: "jian", character: "见面", traditional: "見面", pinyin: "jiànmiàn", meaning: "gặp mặt; hội ngộ", hskLevel: 2, examples: [] },
  { id: "jiandan", character: "简单", traditional: "簡單", pinyin: "jiǎndān", meaning: "đơn giản; giản dị", hskLevel: 2, examples: [] },
  { id: "jiao2", character: "教", traditional: "教", pinyin: "jiāo", meaning: "dạy; dạy học", hskLevel: 2, examples: [] },
  { id: "jie", character: "接", traditional: "接", pinyin: "jiē", meaning: "đón; nhận; tiếp", hskLevel: 2, examples: [] },
  { id: "jin", character: "进", traditional: "進", pinyin: "jìn", meaning: "vào; tiến vào", hskLevel: 2, examples: [] },
  { id: "jin2", character: "近", traditional: "近", pinyin: "jìn", meaning: "gần", hskLevel: 2, examples: [] },
  { id: "jiu2", character: "就", traditional: "就", pinyin: "jiù", meaning: "liền; ngay; chính là", hskLevel: 2, examples: [] },
  { id: "juede", character: "觉得", traditional: "覺得", pinyin: "juéde", meaning: "cảm thấy; cho rằng", hskLevel: 2, examples: [] },
  { id: "kafei", character: "咖啡", traditional: "咖啡", pinyin: "kāfēi", meaning: "cà phê", hskLevel: 2, examples: [] },
  { id: "kanjian", character: "看见", traditional: "看見", pinyin: "kànjiàn", meaning: "nhìn thấy; trông thấy", hskLevel: 2, examples: [] },
  { id: "ke", character: "课", traditional: "課", pinyin: "kè", meaning: "bài học; tiết học; môn học", hskLevel: 2, examples: [] },
  { id: "keqi", character: "客气", traditional: "客氣", pinyin: "kèqi", meaning: "khách sáo; lịch sự", hskLevel: 2, examples: [] },
  { id: "kong", character: "空", traditional: "空", pinyin: "kòng", meaning: "rảnh; trống; không gian", hskLevel: 2, examples: [] },
  { id: "ku", character: "哭", traditional: "哭", pinyin: "kū", meaning: "khóc", hskLevel: 2, examples: [] },
  { id: "kuaile", character: "快乐", traditional: "快樂", pinyin: "kuàilè", meaning: "vui vẻ; hạnh phúc", hskLevel: 2, examples: [] },
  { id: "lei", character: "累", traditional: "累", pinyin: "lèi", meaning: "mệt mỏi; kiệt sức", hskLevel: 2, examples: [] },
  { id: "li2", character: "离", traditional: "離", pinyin: "lí", meaning: "cách; xa cách; rời khỏi", hskLevel: 2, examples: [] },
  { id: "lian", character: "练习", traditional: "練習", pinyin: "liànxí", meaning: "luyện tập; tập luyện", hskLevel: 2, examples: [] },
  { id: "liang", character: "两", traditional: "兩", pinyin: "liǎng", meaning: "hai (2, khi đứng trước lượng từ)", hskLevel: 2, examples: [] },
  { id: "ling", character: "零", traditional: "零", pinyin: "líng", meaning: "không (số 0)", hskLevel: 2, examples: [] },
  { id: "lu", character: "路", traditional: "路", pinyin: "lù", meaning: "đường; con đường", hskLevel: 2, examples: [] },
  { id: "lvxing", character: "旅游", traditional: "旅遊", pinyin: "lǚyóu", meaning: "du lịch; tham quan", hskLevel: 2, examples: [] },
  { id: "mai", character: "买", traditional: "買", pinyin: "mǎi", meaning: "mua", hskLevel: 2, examples: [] },
  { id: "man", character: "慢", traditional: "慢", pinyin: "màn", meaning: "chậm", hskLevel: 2, examples: [] },
  { id: "mao", character: "猫", traditional: "貓", pinyin: "māo", meaning: "con mèo", hskLevel: 2, examples: [] },
  { id: "mei", character: "每", traditional: "每", pinyin: "měi", meaning: "mỗi; từng", hskLevel: 2, examples: [] },
  { id: "meitian", character: "每天", traditional: "每天", pinyin: "měitiān", meaning: "mỗi ngày; hàng ngày", hskLevel: 2, examples: [] },
  { id: "men", character: "门", traditional: "門", pinyin: "mén", meaning: "cửa", hskLevel: 2, examples: [] },
  { id: "mian", character: "面条", traditional: "麵條", pinyin: "miàntiáo", meaning: "mì sợi; bún", hskLevel: 2, examples: [] },
  { id: "na3", character: "拿", traditional: "拿", pinyin: "ná", meaning: "cầm; lấy; mang", hskLevel: 2, examples: [] },
  { id: "nar2", character: "那里", traditional: "那裡", pinyin: "nàlǐ", meaning: "đó; nơi đó; ở đó", hskLevel: 2, examples: [] },
  { id: "nian2", character: "念", traditional: "念", pinyin: "niàn", meaning: "đọc; nhớ tới", hskLevel: 2, examples: [] },
  { id: "nin", character: "您", traditional: "您", pinyin: "nín", meaning: "ông/bà/ngài (kính trọng)", hskLevel: 2, examples: [] },
  { id: "pao", character: "跑步", traditional: "跑步", pinyin: "pǎobù", meaning: "chạy bộ", hskLevel: 2, examples: [] },
  { id: "pian", character: "便宜", traditional: "便宜", pinyin: "piányí", meaning: "rẻ; giá rẻ", hskLevel: 2, examples: [] },
  { id: "piao", character: "票", traditional: "票", pinyin: "piào", meaning: "vé; phiếu", hskLevel: 2, examples: [] },
  { id: "qi2", character: "骑", traditional: "騎", pinyin: "qí", meaning: "cưỡi; lái (xe đạp/xe máy)", hskLevel: 2, examples: [] },
  { id: "qi3", character: "起床", traditional: "起床", pinyin: "qǐchuáng", meaning: "dậy khỏi giường; thức dậy", hskLevel: 2, examples: [] },
  { id: "qian2", character: "铅笔", traditional: "鉛筆", pinyin: "qiānbǐ", meaning: "bút chì", hskLevel: 2, examples: [] },
  { id: "qing2", character: "晴", traditional: "晴", pinyin: "qíng", meaning: "nắng; trời đẹp", hskLevel: 2, examples: [] },
  { id: "qu2", character: "去年", traditional: "去年", pinyin: "qùnián", meaning: "năm ngoái", hskLevel: 2, examples: [] },
  { id: "rang", character: "让", traditional: "讓", pinyin: "ràng", meaning: "để; nhường; cho phép", hskLevel: 2, examples: [] },
  { id: "ri2", character: "日语", traditional: "日語", pinyin: "Rìyǔ", meaning: "tiếng Nhật", hskLevel: 2, examples: [] },
  { id: "rong", character: "容易", traditional: "容易", pinyin: "róngyì", meaning: "dễ dàng; dễ", hskLevel: 2, examples: [] },
  { id: "ru", character: "如果", traditional: "如果", pinyin: "rúguǒ", meaning: "nếu; nếu như; giả sử", hskLevel: 2, examples: [] },
  { id: "san2", character: "上班", traditional: "上班", pinyin: "shàngbān", meaning: "đi làm; bắt đầu ca làm việc", hskLevel: 2, examples: [] },
  { id: "shenti", character: "身体", traditional: "身體", pinyin: "shēntǐ", meaning: "thân thể; sức khỏe", hskLevel: 2, examples: [] },
  { id: "sheng", character: "生病", traditional: "生病", pinyin: "shēngbìng", meaning: "ốm; bị bệnh", hskLevel: 2, examples: [] },
  { id: "shijian", character: "时间", traditional: "時間", pinyin: "shíjiān", meaning: "thời gian", hskLevel: 2, examples: [] },
  { id: "shou", character: "手机", traditional: "手機", pinyin: "shǒujī", meaning: "điện thoại di động", hskLevel: 2, examples: [] },
  { id: "song", character: "送", traditional: "送", pinyin: "sòng", meaning: "tặng; đưa đến; tiễn", hskLevel: 2, examples: [] },
  { id: "su", character: "虽然", traditional: "雖然", pinyin: "suīrán", meaning: "mặc dù; tuy nhiên", hskLevel: 2, examples: [] },
  { id: "tai2", character: "踢足球", traditional: "踢足球", pinyin: "tī zúqiú", meaning: "đá bóng; chơi bóng đá", hskLevel: 2, examples: [] },
  { id: "tian", character: "甜", traditional: "甜", pinyin: "tián", meaning: "ngọt", hskLevel: 2, examples: [] },
  { id: "tiao", character: "跳舞", traditional: "跳舞", pinyin: "tiàowǔ", meaning: "nhảy múa; khiêu vũ", hskLevel: 2, examples: [] },
  { id: "wai", character: "外", traditional: "外", pinyin: "wài", meaning: "ngoài; bên ngoài", hskLevel: 2, examples: [] },
  { id: "wan", character: "完", traditional: "完", pinyin: "wán", meaning: "xong; hoàn thành; hết", hskLevel: 2, examples: [] },
  { id: "wan2", character: "玩", traditional: "玩", pinyin: "wán", meaning: "chơi; vui chơi", hskLevel: 2, examples: [] },
  { id: "wang", character: "忘", traditional: "忘", pinyin: "wàng", meaning: "quên; lãng quên", hskLevel: 2, examples: [] },
  { id: "wei2", character: "为什么", traditional: "為什麼", pinyin: "wèishénme", meaning: "tại sao; vì sao", hskLevel: 2, examples: [] },
  { id: "wen", character: "问", traditional: "問", pinyin: "wèn", meaning: "hỏi; chất vấn", hskLevel: 2, examples: [] },
  { id: "wenti", character: "问题", traditional: "問題", pinyin: "wèntí", meaning: "câu hỏi; vấn đề", hskLevel: 2, examples: [] },
  { id: "xi", character: "希望", traditional: "希望", pinyin: "xīwàng", meaning: "hy vọng; mong muốn", hskLevel: 2, examples: [] },
  { id: "xiao2", character: "笑", traditional: "笑", pinyin: "xiào", meaning: "cười", hskLevel: 2, examples: [] },
  { id: "xin", character: "新", traditional: "新", pinyin: "xīn", meaning: "mới; mới mẻ", hskLevel: 2, examples: [] },
  { id: "xuan", character: "选择", traditional: "選擇", pinyin: "xuǎnzé", meaning: "lựa chọn; chọn lựa", hskLevel: 2, examples: [] },
  { id: "yan", character: "颜色", traditional: "顏色", pinyin: "yánsè", meaning: "màu sắc; màu", hskLevel: 2, examples: [] },
  { id: "yao", character: "药", traditional: "藥", pinyin: "yào", meaning: "thuốc", hskLevel: 2, examples: [] },
  { id: "yao2", character: "要", traditional: "要", pinyin: "yào", meaning: "muốn; cần; sẽ", hskLevel: 2, examples: [] },
  { id: "ye", character: "也", traditional: "也", pinyin: "yě", meaning: "cũng; cũng vậy", hskLevel: 2, examples: [] },
  { id: "yiqi", character: "一起", traditional: "一起", pinyin: "yīqǐ", meaning: "cùng nhau; cùng", hskLevel: 2, examples: [] },
  { id: "yiyang", character: "一样", traditional: "一樣", pinyin: "yīyàng", meaning: "giống nhau; như nhau", hskLevel: 2, examples: [] },
  { id: "yingyu", character: "英语", traditional: "英語", pinyin: "Yīngyǔ", meaning: "tiếng Anh", hskLevel: 2, examples: [] },
  { id: "yong", character: "用", traditional: "用", pinyin: "yòng", meaning: "dùng; sử dụng", hskLevel: 2, examples: [] },
  { id: "you2", character: "游泳", traditional: "游泳", pinyin: "yóuyǒng", meaning: "bơi lội; bơi", hskLevel: 2, examples: [] },
  { id: "you3", character: "有名", traditional: "有名", pinyin: "yǒumíng", meaning: "nổi tiếng; có tiếng", hskLevel: 2, examples: [] },
  { id: "yuan", character: "元", traditional: "元", pinyin: "yuán", meaning: "nhân dân tệ (tiền Trung Quốc)", hskLevel: 2, examples: [] },
  { id: "yundong", character: "运动", traditional: "運動", pinyin: "yùndòng", meaning: "thể thao; vận động", hskLevel: 2, examples: [] },
  { id: "zai2", character: "再", traditional: "再", pinyin: "zài", meaning: "lại; nữa; thêm", hskLevel: 2, examples: [] },
  { id: "zhang", character: "张", traditional: "張", pinyin: "zhāng", meaning: "(lượng từ cho tờ giấy, bàn)", hskLevel: 2, examples: [] },
  { id: "zhao", character: "找", traditional: "找", pinyin: "zhǎo", meaning: "tìm; tìm kiếm", hskLevel: 2, examples: [] },
  { id: "zhe2", character: "着", traditional: "著", pinyin: "zhe", meaning: "(trợ từ diễn tiến)", hskLevel: 2, examples: [] },
  { id: "zhi", character: "知道", traditional: "知道", pinyin: "zhīdào", meaning: "biết; biết rõ", hskLevel: 2, examples: [] },
  { id: "zhun", character: "准备", traditional: "準備", pinyin: "zhǔnbèi", meaning: "chuẩn bị; sẵn sàng", hskLevel: 2, examples: [] },
  { id: "zi2", character: "自行车", traditional: "自行車", pinyin: "zìxíngchē", meaning: "xe đạp", hskLevel: 2, examples: [] },
  { id: "zou", character: "走", traditional: "走", pinyin: "zǒu", meaning: "đi; bước đi", hskLevel: 2, examples: [] },
  { id: "zui", character: "最", traditional: "最", pinyin: "zuì", meaning: "nhất; most; nhất trong số", hskLevel: 2, examples: [] },
  { id: "zuojin", character: "最近", traditional: "最近", pinyin: "zuìjìn", meaning: "gần đây; dạo này", hskLevel: 2, examples: [] },

  // HSK 3
  { id: "anfang", character: "安静", traditional: "安靜", pinyin: "ānjìng", meaning: "yên tĩnh; lặng yên", hskLevel: 3, examples: [] },
  { id: "banfa", character: "办法", traditional: "辦法", pinyin: "bànfǎ", meaning: "cách thức; biện pháp", hskLevel: 3, examples: [] },
  { id: "bangmang", character: "帮忙", traditional: "幫忙", pinyin: "bāngmáng", meaning: "giúp đỡ; phụ giúp", hskLevel: 3, examples: [] },
  { id: "bao2", character: "包", traditional: "包", pinyin: "bāo", meaning: "túi; bao; gói", hskLevel: 3, examples: [] },
  { id: "ben2", character: "本来", traditional: "本來", pinyin: "běnlái", meaning: "vốn dĩ; lẽ ra; ban đầu", hskLevel: 3, examples: [] },
  { id: "biaoyan", character: "表演", traditional: "表演", pinyin: "biǎoyǎn", meaning: "biểu diễn; trình diễn", hskLevel: 3, examples: [] },
  { id: "bingqilinn", character: "冰淇淋", traditional: "冰淇淋", pinyin: "bīngqílín", meaning: "kem lạnh", hskLevel: 3, examples: [] },
  { id: "caidan", character: "菜单", traditional: "菜單", pinyin: "càidān", meaning: "thực đơn; menu", hskLevel: 3, examples: [] },
  { id: "chao", character: "超市", traditional: "超市", pinyin: "chāoshì", meaning: "siêu thị", hskLevel: 3, examples: [] },
  { id: "chen", character: "衬衫", traditional: "襯衫", pinyin: "chènshān", meaning: "áo sơ mi", hskLevel: 3, examples: [] },
  { id: "chuan", character: "船", traditional: "船", pinyin: "chuán", meaning: "tàu thuyền; thuyền", hskLevel: 3, examples: [] },
  { id: "chuang", character: "窗户", traditional: "窗戶", pinyin: "chuānghu", meaning: "cửa sổ", hskLevel: 3, examples: [] },
  { id: "ci", character: "词典", traditional: "詞典", pinyin: "cídiǎn", meaning: "từ điển", hskLevel: 3, examples: [] },
  { id: "cong", character: "从", traditional: "從", pinyin: "cóng", meaning: "từ; từ khi; từ lúc", hskLevel: 3, examples: [] },
  { id: "dai", character: "带", traditional: "帶", pinyin: "dài", meaning: "mang theo; đem theo; đưa", hskLevel: 3, examples: [] },
  { id: "dajia2", character: "担心", traditional: "擔心", pinyin: "dānxīn", meaning: "lo lắng; lo ngại", hskLevel: 3, examples: [] },
  { id: "dang", character: "当", traditional: "當", pinyin: "dāng", meaning: "khi; là; làm (vai trò gì đó)", hskLevel: 3, examples: [] },
  { id: "dao2", character: "导游", traditional: "導遊", pinyin: "dǎoyóu", meaning: "hướng dẫn viên du lịch", hskLevel: 3, examples: [] },
  { id: "deng2", character: "灯", traditional: "燈", pinyin: "dēng", meaning: "đèn; ánh đèn", hskLevel: 3, examples: [] },
  { id: "difang", character: "地方", traditional: "地方", pinyin: "dìfang", meaning: "nơi chốn; địa điểm", hskLevel: 3, examples: [] },
  { id: "ditu", character: "地图", traditional: "地圖", pinyin: "dìtú", meaning: "bản đồ", hskLevel: 3, examples: [] },
  { id: "diyi", character: "第一", traditional: "第一", pinyin: "dìyī", meaning: "thứ nhất; đầu tiên", hskLevel: 3, examples: [] },
  { id: "donghwa", character: "动物", traditional: "動物", pinyin: "dòngwù", meaning: "động vật", hskLevel: 3, examples: [] },
  { id: "duan", character: "段", traditional: "段", pinyin: "duàn", meaning: "đoạn; giai đoạn", hskLevel: 3, examples: [] },
  { id: "duanxi", character: "锻炼", traditional: "鍛鍊", pinyin: "duànliàn", meaning: "luyện tập thể chất", hskLevel: 3, examples: [] },
  { id: "e", character: "鹅", traditional: "鵝", pinyin: "é", meaning: "ngỗng", hskLevel: 3, examples: [] },
  { id: "er2", character: "而且", traditional: "而且", pinyin: "érqiě", meaning: "hơn nữa; và còn", hskLevel: 3, examples: [] },
  { id: "fangfa", character: "方法", traditional: "方法", pinyin: "fāngfǎ", meaning: "phương pháp; cách thức", hskLevel: 3, examples: [] },
  { id: "fangmian", character: "方面", traditional: "方面", pinyin: "fāngmiàn", meaning: "phương diện; mặt; khía cạnh", hskLevel: 3, examples: [] },
  { id: "fen2", character: "分钟", traditional: "分鐘", pinyin: "fēnzhōng", meaning: "phút đồng hồ", hskLevel: 3, examples: [] },
  { id: "fu2", character: "附近", traditional: "附近", pinyin: "fùjìn", meaning: "gần đây; lân cận; xung quanh", hskLevel: 3, examples: [] },
  { id: "gang", character: "刚才", traditional: "剛才", pinyin: "gāngcái", meaning: "vừa rồi; mới đây", hskLevel: 3, examples: [] },
  { id: "ge3", character: "各种", traditional: "各種", pinyin: "gèzhǒng", meaning: "các loại; đủ loại", hskLevel: 3, examples: [] },
  { id: "gen", character: "跟", traditional: "跟", pinyin: "gēn", meaning: "với; cùng với; và", hskLevel: 3, examples: [] },
  { id: "guo2", character: "国际", traditional: "國際", pinyin: "guójì", meaning: "quốc tế; quốc tế hóa", hskLevel: 3, examples: [] },
  { id: "guojia", character: "国家", traditional: "國家", pinyin: "guójiā", meaning: "quốc gia; đất nước", hskLevel: 3, examples: [] },
  { id: "han", character: "汗", traditional: "汗", pinyin: "hàn", meaning: "mồ hôi", hskLevel: 3, examples: [] },
  { id: "he4", character: "河", traditional: "河", pinyin: "hé", meaning: "sông; dòng sông", hskLevel: 3, examples: [] },
  { id: "hua2", character: "画", traditional: "畫", pinyin: "huà", meaning: "vẽ; tranh vẽ", hskLevel: 3, examples: [] },
  { id: "huangjin", character: "黄金", traditional: "黃金", pinyin: "huángjīn", meaning: "vàng", hskLevel: 3, examples: [] },
  { id: "jian2", character: "健康", traditional: "健康", pinyin: "jiànkāng", meaning: "khỏe mạnh; sức khỏe", hskLevel: 3, examples: [] },
  { id: "jiao3", character: "脚", traditional: "腳", pinyin: "jiǎo", meaning: "chân; bàn chân", hskLevel: 3, examples: [] },
  { id: "jiejie", character: "姐姐", traditional: "姐姐", pinyin: "jiějie", meaning: "chị gái", hskLevel: 3, examples: [] },
  { id: "jintian2", character: "经常", traditional: "經常", pinyin: "jīngcháng", meaning: "thường xuyên; hay", hskLevel: 3, examples: [] },
  { id: "jiu3", character: "旧", traditional: "舊", pinyin: "jiù", meaning: "cũ; cũ kỹ", hskLevel: 3, examples: [] },
  { id: "ju", character: "句子", traditional: "句子", pinyin: "jùzi", meaning: "câu; câu văn", hskLevel: 3, examples: [] },
  { id: "jue", character: "决定", traditional: "決定", pinyin: "juédìng", meaning: "quyết định", hskLevel: 3, examples: [] },
  { id: "ka", character: "卡", traditional: "卡", pinyin: "kǎ", meaning: "thẻ; card", hskLevel: 3, examples: [] },
  { id: "kai2", character: "开始", traditional: "開始", pinyin: "kāishǐ", meaning: "bắt đầu", hskLevel: 3, examples: [] },
  { id: "kao", character: "考试", traditional: "考試", pinyin: "kǎoshì", meaning: "thi; bài thi; kỳ thi", hskLevel: 3, examples: [] },
  { id: "kou", character: "口", traditional: "口", pinyin: "kǒu", meaning: "miệng; cửa", hskLevel: 3, examples: [] },
  { id: "ku2", character: "苦", traditional: "苦", pinyin: "kǔ", meaning: "đắng; khổ cực", hskLevel: 3, examples: [] },
  { id: "lan", character: "蓝", traditional: "藍", pinyin: "lán", meaning: "xanh lam; màu xanh", hskLevel: 3, examples: [] },
  { id: "laoshi2", character: "老实", traditional: "老實", pinyin: "lǎoshi", meaning: "thật thà; thành thật", hskLevel: 3, examples: [] },
  { id: "lazi", character: "辣", traditional: "辣", pinyin: "là", meaning: "cay", hskLevel: 3, examples: [] },
  { id: "leng2", character: "冷静", traditional: "冷靜", pinyin: "lěngjìng", meaning: "bình tĩnh; điềm tĩnh", hskLevel: 3, examples: [] },
  { id: "li3", character: "礼物", traditional: "禮物", pinyin: "lǐwù", meaning: "quà tặng; quà", hskLevel: 3, examples: [] },
  { id: "liji", character: "例如", traditional: "例如", pinyin: "lìrú", meaning: "ví dụ; chẳng hạn", hskLevel: 3, examples: [] },
  { id: "ling2", character: "另外", traditional: "另外", pinyin: "lìngwài", meaning: "ngoài ra; thêm vào đó", hskLevel: 3, examples: [] },
  { id: "liu2", character: "留", traditional: "留", pinyin: "liú", meaning: "ở lại; lưu giữ; để lại", hskLevel: 3, examples: [] },
  { id: "lv", character: "绿", traditional: "綠", pinyin: "lǜ", meaning: "xanh lá; màu xanh lá", hskLevel: 3, examples: [] },
  { id: "ma", character: "马", traditional: "馬", pinyin: "mǎ", meaning: "con ngựa", hskLevel: 3, examples: [] },
  { id: "mao2", character: "帽子", traditional: "帽子", pinyin: "màozi", meaning: "mũ; nón", hskLevel: 3, examples: [] },
  { id: "meiguo", character: "美国", traditional: "美國", pinyin: "Měiguó", meaning: "Hoa Kỳ; Mỹ", hskLevel: 3, examples: [] },
  { id: "meimei", character: "妹妹", traditional: "妹妹", pinyin: "mèimei", meaning: "em gái", hskLevel: 3, examples: [] },
  { id: "men2", character: "们", traditional: "們", pinyin: "men", meaning: "(hậu tố số nhiều)", hskLevel: 3, examples: [] },
  { id: "nali", character: "那里", traditional: "那裡", pinyin: "nàlǐ", meaning: "đó; ở đó", hskLevel: 3, examples: [] },
  { id: "nande", character: "难", traditional: "難", pinyin: "nán", meaning: "khó; khó khăn", hskLevel: 3, examples: [] },
  { id: "nan", character: "南", traditional: "南", pinyin: "nán", meaning: "phía nam; phương nam", hskLevel: 3, examples: [] },
  { id: "nian3", character: "年级", traditional: "年級", pinyin: "niánjí", meaning: "khối lớp; năm học", hskLevel: 3, examples: [] },
  { id: "pang", character: "旁边", traditional: "旁邊", pinyin: "pángbiān", meaning: "bên cạnh; kế bên", hskLevel: 3, examples: [] },
  { id: "pei", character: "陪", traditional: "陪", pinyin: "péi", meaning: "đi cùng; đồng hành; bầu bạn", hskLevel: 3, examples: [] },
  { id: "pi", character: "皮", traditional: "皮", pinyin: "pí", meaning: "da; vỏ", hskLevel: 3, examples: [] },
  { id: "pian2", character: "篇", traditional: "篇", pinyin: "piān", meaning: "(lượng từ cho bài viết, bài báo)", hskLevel: 3, examples: [] },
  { id: "ping", character: "瓶子", traditional: "瓶子", pinyin: "píngzi", meaning: "chai; lọ; bình", hskLevel: 3, examples: [] },
  { id: "qi4", character: "其实", traditional: "其實", pinyin: "qíshí", meaning: "thực ra; thực tế là", hskLevel: 3, examples: [] },
  { id: "qi5", character: "气候", traditional: "氣候", pinyin: "qìhòu", meaning: "khí hậu", hskLevel: 3, examples: [] },
  { id: "qian3", character: "铅笔", traditional: "鉛筆", pinyin: "qiānbǐ", meaning: "bút chì", hskLevel: 3, examples: [] },
  { id: "qing3", character: "情况", traditional: "情況", pinyin: "qíngkuàng", meaning: "tình hình; tình trạng", hskLevel: 3, examples: [] },
  { id: "qu3", character: "取", traditional: "取", pinyin: "qǔ", meaning: "lấy; lấy ra; chọn", hskLevel: 3, examples: [] },
  { id: "ran", character: "然后", traditional: "然後", pinyin: "ránhòu", meaning: "sau đó; rồi thì", hskLevel: 3, examples: [] },
  { id: "ren2", character: "认真", traditional: "認真", pinyin: "rènzhēn", meaning: "nghiêm túc; cẩn thận", hskLevel: 3, examples: [] },
  { id: "ri3", character: "日记", traditional: "日記", pinyin: "rìjì", meaning: "nhật ký", hskLevel: 3, examples: [] },
  { id: "shan", character: "山", traditional: "山", pinyin: "shān", meaning: "núi; đồi", hskLevel: 3, examples: [] },
  { id: "shang2", character: "上网", traditional: "上網", pinyin: "shàngwǎng", meaning: "lên mạng; truy cập internet", hskLevel: 3, examples: [] },
  { id: "shen", character: "深", traditional: "深", pinyin: "shēn", meaning: "sâu; sâu sắc; đậm", hskLevel: 3, examples: [] },
  { id: "shenghuo", character: "生活", traditional: "生活", pinyin: "shēnghuó", meaning: "cuộc sống; sinh hoạt", hskLevel: 3, examples: [] },
  { id: "shengyin", character: "声音", traditional: "聲音", pinyin: "shēngyīn", meaning: "âm thanh; tiếng; giọng nói", hskLevel: 3, examples: [] },
  { id: "shu2", character: "舒服", traditional: "舒服", pinyin: "shūfu", meaning: "thoải mái; dễ chịu", hskLevel: 3, examples: [] },
  { id: "shuang", character: "双", traditional: "雙", pinyin: "shuāng", meaning: "đôi; cặp", hskLevel: 3, examples: [] },
  { id: "si2", character: "思想", traditional: "思想", pinyin: "sīxiǎng", meaning: "tư tưởng; suy nghĩ", hskLevel: 3, examples: [] },
  { id: "ta3", character: "它", traditional: "它", pinyin: "tā", meaning: "nó; cái đó (không phải người)", hskLevel: 3, examples: [] },
  { id: "tang", character: "糖", traditional: "糖", pinyin: "táng", meaning: "đường; kẹo ngọt", hskLevel: 3, examples: [] },
  { id: "tao", character: "套", traditional: "套", pinyin: "tào", meaning: "bộ; tập; bao; lồng vào", hskLevel: 3, examples: [] },
  { id: "te", character: "特别", traditional: "特別", pinyin: "tèbié", meaning: "đặc biệt; đặc biệt là", hskLevel: 3, examples: [] },
  { id: "ti2", character: "体育", traditional: "體育", pinyin: "tǐyù", meaning: "thể dục; thể thao", hskLevel: 3, examples: [] },
  { id: "ti3", character: "提高", traditional: "提高", pinyin: "tígāo", meaning: "nâng cao; cải thiện", hskLevel: 3, examples: [] },
  { id: "tian2", character: "填", traditional: "填", pinyin: "tián", meaning: "điền; điền vào", hskLevel: 3, examples: [] },
  { id: "tong", character: "同事", traditional: "同事", pinyin: "tóngshì", meaning: "đồng nghiệp", hskLevel: 3, examples: [] },
  { id: "tu", character: "图书馆", traditional: "圖書館", pinyin: "túshūguǎn", meaning: "thư viện", hskLevel: 3, examples: [] },
  { id: "wan3", character: "晚上", traditional: "晚上", pinyin: "wǎnshang", meaning: "buổi tối; tối", hskLevel: 3, examples: [] },
  { id: "wei3", character: "位置", traditional: "位置", pinyin: "wèizhì", meaning: "vị trí; chỗ", hskLevel: 3, examples: [] },
  { id: "xi2", character: "习惯", traditional: "習慣", pinyin: "xíguàn", meaning: "thói quen; quen thuộc", hskLevel: 3, examples: [] },
  { id: "xian", character: "线", traditional: "線", pinyin: "xiàn", meaning: "đường; dây; tuyến", hskLevel: 3, examples: [] },
  { id: "xiao3", character: "小时", traditional: "小時", pinyin: "xiǎoshí", meaning: "giờ đồng hồ; tiếng", hskLevel: 3, examples: [] },
  { id: "xin2", character: "信", traditional: "信", pinyin: "xìn", meaning: "thư; tin nhắn; tin tưởng", hskLevel: 3, examples: [] },
  { id: "xing", character: "行", traditional: "行", pinyin: "xíng", meaning: "được; có thể; đi bộ", hskLevel: 3, examples: [] },
  { id: "xu", character: "需要", traditional: "需要", pinyin: "xūyào", meaning: "cần; cần thiết", hskLevel: 3, examples: [] },
  { id: "ya", character: "牙", traditional: "牙", pinyin: "yá", meaning: "răng", hskLevel: 3, examples: [] },
  { id: "yang", character: "样", traditional: "樣", pinyin: "yàng", meaning: "dạng; kiểu; loại", hskLevel: 3, examples: [] },
  { id: "yi2", character: "已经", traditional: "已經", pinyin: "yǐjīng", meaning: "đã; rồi; đã rồi", hskLevel: 3, examples: [] },
  { id: "yin", character: "因为", traditional: "因為", pinyin: "yīnwèi", meaning: "vì; bởi vì", hskLevel: 3, examples: [] },
  { id: "yinyue", character: "音乐", traditional: "音樂", pinyin: "yīnyuè", meaning: "âm nhạc; nhạc", hskLevel: 3, examples: [] },
  { id: "yong2", character: "勇敢", traditional: "勇敢", pinyin: "yǒnggǎn", meaning: "dũng cảm; can đảm", hskLevel: 3, examples: [] },
  { id: "you4", character: "游戏", traditional: "遊戲", pinyin: "yóuxì", meaning: "trò chơi; game", hskLevel: 3, examples: [] },
  { id: "yu", character: "语言", traditional: "語言", pinyin: "yǔyán", meaning: "ngôn ngữ", hskLevel: 3, examples: [] },
  { id: "yue2", character: "约", traditional: "約", pinyin: "yuē", meaning: "hẹn; ước chừng", hskLevel: 3, examples: [] },
  { id: "ze", character: "这里", traditional: "這裡", pinyin: "zhèlǐ", meaning: "đây; nơi này; ở đây", hskLevel: 3, examples: [] },
  { id: "zhan", character: "站", traditional: "站", pinyin: "zhàn", meaning: "đứng; trạm (xe buýt, tàu)", hskLevel: 3, examples: [] },
  { id: "zhang2", character: "长", traditional: "長", pinyin: "zhǎng", meaning: "dài; lớn lên; trưởng thành", hskLevel: 3, examples: [] },
  { id: "zheng", character: "正在", traditional: "正在", pinyin: "zhèngzài", meaning: "đang; đang trong lúc", hskLevel: 3, examples: [] },
  { id: "zhi2", character: "只有", traditional: "只有", pinyin: "zhǐyǒu", meaning: "chỉ có; chỉ khi", hskLevel: 3, examples: [] },
  { id: "zhong", character: "重要", traditional: "重要", pinyin: "zhòngyào", meaning: "quan trọng", hskLevel: 3, examples: [] },
  { id: "zhou", character: "周末", traditional: "週末", pinyin: "zhōumò", meaning: "cuối tuần", hskLevel: 3, examples: [] },
  { id: "zhu2", character: "主意", traditional: "主意", pinyin: "zhǔyi", meaning: "ý kiến; kế hoạch; ý tưởng", hskLevel: 3, examples: [] },
  { id: "zhun2", character: "准确", traditional: "準確", pinyin: "zhǔnquè", meaning: "chính xác; đúng đắn", hskLevel: 3, examples: [] },

  // HSK 4
  { id: "baohu", character: "保护", traditional: "保護", pinyin: "bǎohù", meaning: "bảo vệ; che chở", hskLevel: 4, examples: [] },
  { id: "bihe", character: "比较", traditional: "比較", pinyin: "bǐjiào", meaning: "so sánh; tương đối; khá", hskLevel: 4, examples: [] },
  { id: "bufen", character: "部分", traditional: "部分", pinyin: "bùfen", meaning: "phần; bộ phận", hskLevel: 4, examples: [] },
  { id: "canjia", character: "参加", traditional: "參加", pinyin: "cānjiā", meaning: "tham gia; dự", hskLevel: 4, examples: [] },
  { id: "chengji", character: "成绩", traditional: "成績", pinyin: "chéngjì", meaning: "thành tích; điểm số", hskLevel: 4, examples: [] },
  { id: "chenggong", character: "成功", traditional: "成功", pinyin: "chénggōng", meaning: "thành công", hskLevel: 4, examples: [] },
  { id: "chouyuan", character: "重复", traditional: "重複", pinyin: "chóngfù", meaning: "lặp lại; nhắc lại", hskLevel: 4, examples: [] },
  { id: "chuban", character: "出版", traditional: "出版", pinyin: "chūbǎn", meaning: "xuất bản; phát hành", hskLevel: 4, examples: [] },
  { id: "chufa", character: "出发", traditional: "出發", pinyin: "chūfā", meaning: "khởi hành; xuất phát", hskLevel: 4, examples: [] },
  { id: "daibiao", character: "代表", traditional: "代表", pinyin: "dàibiǎo", meaning: "đại diện; đại biểu", hskLevel: 4, examples: [] },
  { id: "daxue", character: "大学", traditional: "大學", pinyin: "dàxué", meaning: "đại học; trường đại học", hskLevel: 4, examples: [] },
  { id: "dingdan", character: "订单", traditional: "訂單", pinyin: "dìngdān", meaning: "đơn hàng; đặt hàng", hskLevel: 4, examples: [] },
  { id: "duihua", character: "对话", traditional: "對話", pinyin: "duìhuà", meaning: "đối thoại; hội thoại", hskLevel: 4, examples: [] },
  { id: "fa", character: "发展", traditional: "發展", pinyin: "fāzhǎn", meaning: "phát triển", hskLevel: 4, examples: [] },
  { id: "fanyi", character: "翻译", traditional: "翻譯", pinyin: "fānyì", meaning: "dịch; phiên dịch", hskLevel: 4, examples: [] },
  { id: "fuzhu", character: "负责", traditional: "負責", pinyin: "fùzé", meaning: "chịu trách nhiệm; có trách nhiệm", hskLevel: 4, examples: [] },
  { id: "gongyi", character: "公园", traditional: "公園", pinyin: "gōngyuán", meaning: "công viên", hskLevel: 4, examples: [] },
  { id: "guanxi", character: "关系", traditional: "關係", pinyin: "guānxi", meaning: "quan hệ; mối quan hệ", hskLevel: 4, examples: [] },
  { id: "jieshao", character: "介绍", traditional: "介紹", pinyin: "jièshào", meaning: "giới thiệu", hskLevel: 4, examples: [] },
  { id: "jingli", character: "经历", traditional: "經歷", pinyin: "jīnglì", meaning: "kinh nghiệm; trải nghiệm", hskLevel: 4, examples: [] },
  { id: "jingji", character: "经济", traditional: "經濟", pinyin: "jīngjì", meaning: "kinh tế", hskLevel: 4, examples: [] },
  { id: "kexue", character: "科学", traditional: "科學", pinyin: "kēxué", meaning: "khoa học", hskLevel: 4, examples: [] },
  { id: "lishi", character: "历史", traditional: "歷史", pinyin: "lìshǐ", meaning: "lịch sử", hskLevel: 4, examples: [] },
  { id: "mubiao", character: "目标", traditional: "目標", pinyin: "mùbiāo", meaning: "mục tiêu; mục đích", hskLevel: 4, examples: [] },
  { id: "piping", character: "批评", traditional: "批評", pinyin: "pīpíng", meaning: "phê bình; chỉ trích", hskLevel: 4, examples: [] },
  { id: "qinqi", character: "亲切", traditional: "親切", pinyin: "qīnqiè", meaning: "thân thiết; ân cần", hskLevel: 4, examples: [] },
  { id: "shehui", character: "社会", traditional: "社會", pinyin: "shèhuì", meaning: "xã hội", hskLevel: 4, examples: [] },
  { id: "shuoming", character: "说明", traditional: "說明", pinyin: "shuōmíng", meaning: "giải thích; thuyết minh", hskLevel: 4, examples: [] },
  { id: "wenhua", character: "文化", traditional: "文化", pinyin: "wénhuà", meaning: "văn hóa", hskLevel: 4, examples: [] },
  { id: "xiaoxi", character: "消息", traditional: "消息", pinyin: "xiāoxi", meaning: "tin tức; thông tin", hskLevel: 4, examples: [] },
  { id: "xinli", character: "心理", traditional: "心理", pinyin: "xīnlǐ", meaning: "tâm lý", hskLevel: 4, examples: [] },
  { id: "yanjiu", character: "研究", traditional: "研究", pinyin: "yánjiū", meaning: "nghiên cứu", hskLevel: 4, examples: [] },
  { id: "yijian", character: "意见", traditional: "意見", pinyin: "yìjiàn", meaning: "ý kiến; quan điểm", hskLevel: 4, examples: [] },
  { id: "zhengque", character: "正确", traditional: "正確", pinyin: "zhèngquè", meaning: "đúng; chính xác", hskLevel: 4, examples: [] },

  // HSK 5
  { id: "biaoda", character: "表达", traditional: "表達", pinyin: "biǎodá", meaning: "biểu đạt; diễn đạt", hskLevel: 5, examples: [] },
  { id: "fangshi", character: "方式", traditional: "方式", pinyin: "fāngshì", meaning: "phương thức; cách thức", hskLevel: 5, examples: [] },
  { id: "gexing", character: "个性", traditional: "個性", pinyin: "gèxìng", meaning: "tính cách; cá tính", hskLevel: 5, examples: [] },
  { id: "guocheng", character: "过程", traditional: "過程", pinyin: "guòchéng", meaning: "quá trình", hskLevel: 5, examples: [] },
  { id: "jingyan", character: "经验", traditional: "經驗", pinyin: "jīngyàn", meaning: "kinh nghiệm", hskLevel: 5, examples: [] },
  { id: "jueshuo", character: "决心", traditional: "決心", pinyin: "juéxīn", meaning: "quyết tâm", hskLevel: 5, examples: [] },
  { id: "kongjian", character: "空间", traditional: "空間", pinyin: "kōngjiān", meaning: "không gian", hskLevel: 5, examples: [] },
  { id: "lilun", character: "理论", traditional: "理論", pinyin: "lǐlùn", meaning: "lý luận; lý thuyết", hskLevel: 5, examples: [] },
  { id: "neirong", character: "内容", traditional: "內容", pinyin: "nèiróng", meaning: "nội dung", hskLevel: 5, examples: [] },
  { id: "peiyang", character: "培养", traditional: "培養", pinyin: "péiyǎng", meaning: "bồi dưỡng; nuôi dưỡng; đào tạo", hskLevel: 5, examples: [] },
  { id: "quanbu", character: "全部", traditional: "全部", pinyin: "quánbù", meaning: "toàn bộ; tất cả", hskLevel: 5, examples: [] },
  { id: "renwei", character: "认为", traditional: "認為", pinyin: "rènwéi", meaning: "cho rằng; nghĩ rằng", hskLevel: 5, examples: [] },
  { id: "shoufa", character: "受到", traditional: "受到", pinyin: "shòudào", meaning: "nhận được; bị (ảnh hưởng)", hskLevel: 5, examples: [] },
  { id: "tiaozhan", character: "挑战", traditional: "挑戰", pinyin: "tiǎozhàn", meaning: "thách thức", hskLevel: 5, examples: [] },
  { id: "wenming", character: "文明", traditional: "文明", pinyin: "wénmíng", meaning: "văn minh; nền văn minh", hskLevel: 5, examples: [] },
  { id: "xiandai", character: "现代", traditional: "現代", pinyin: "xiàndài", meaning: "hiện đại", hskLevel: 5, examples: [] },
  { id: "zonghe", character: "综合", traditional: "綜合", pinyin: "zōnghé", meaning: "tổng hợp; toàn diện", hskLevel: 5, examples: [] },

  // HSK 6
  { id: "biankang", character: "辩论", traditional: "辯論", pinyin: "biànlùn", meaning: "tranh luận; biện hộ", hskLevel: 6, examples: [] },
  { id: "chuangxin", character: "创新", traditional: "創新", pinyin: "chuàngxīn", meaning: "đổi mới; sáng tạo", hskLevel: 6, examples: [] },
  { id: "guangming", character: "光明", traditional: "光明", pinyin: "guāngmíng", meaning: "sáng sủa; quang minh", hskLevel: 6, examples: [] },
  { id: "hexie", character: "和谐", traditional: "和諧", pinyin: "héxié", meaning: "hòa hợp; hài hòa", hskLevel: 6, examples: [] },
  { id: "jizhong", character: "集中", traditional: "集中", pinyin: "jízhōng", meaning: "tập trung; tập hợp", hskLevel: 6, examples: [] },
  { id: "pubian", character: "普遍", traditional: "普遍", pinyin: "pǔbiàn", meaning: "phổ biến; phổ quát", hskLevel: 6, examples: [] },
  { id: "qiyue", character: "启发", traditional: "啟發", pinyin: "qǐfā", meaning: "khơi dậy; khai sáng; gợi mở", hskLevel: 6, examples: [] },
  { id: "shenhua", character: "深化", traditional: "深化", pinyin: "shēnhuà", meaning: "sâu sắc hơn; đào sâu", hskLevel: 6, examples: [] },
  { id: "tuidong", character: "推动", traditional: "推動", pinyin: "tuīdòng", meaning: "thúc đẩy; đẩy mạnh", hskLevel: 6, examples: [] },
  { id: "wanzheng", character: "完整", traditional: "完整", pinyin: "wánzhěng", meaning: "hoàn chỉnh; toàn vẹn", hskLevel: 6, examples: [] },
  { id: "yanbian", character: "演变", traditional: "演變", pinyin: "yǎnbiàn", meaning: "diễn biến; tiến hóa", hskLevel: 6, examples: [] },
  { id: "zhanlu", character: "战略", traditional: "戰略", pinyin: "zhànlüè", meaning: "chiến lược", hskLevel: 6, examples: [] },
];

export const HSK_LEVELS = [
  { level: 1, name: "HSK 1", description: "Từ cơ bản", wordCount: 150, color: "#E53935" },
  { level: 2, name: "HSK 2", description: "Giao tiếp đơn giản", wordCount: 300, color: "#FB8C00" },
  { level: 3, name: "HSK 3", description: "Giao tiếp thông thường", wordCount: 600, color: "#43A047" },
  { level: 4, name: "HSK 4", description: "Giao tiếp lưu loát", wordCount: 1200, color: "#1E88E5" },
  { level: 5, name: "HSK 5", description: "Trình độ cao", wordCount: 2500, color: "#8E24AA" },
  { level: 6, name: "HSK 6", description: "Thành thạo", wordCount: 5000, color: "#455A64" },
];

export function getWordsByHSK(level: number): Word[] {
  return HSK_WORDS.filter((w) => w.hskLevel === level);
}

export function searchWords(query: string): Word[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  return HSK_WORDS.filter(
    (w) =>
      w.character.includes(q) ||
      w.traditional.includes(q) ||
      w.pinyin.toLowerCase().includes(q) ||
      w.meaning.toLowerCase().includes(q)
  ).slice(0, 40);
}

export function getWordById(id: string): Word | undefined {
  return HSK_WORDS.find((w) => w.id === id);
}
