import { HSKQuestion } from "@/types/hskExam";

export const QUESTION_BANK: HSKQuestion[] = [
  // ==========================================
  // HSK 1 QUESTIONS
  // ==========================================
  {
    id: "hsk1_lis_01",
    level: 1,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_short",
    difficulty: "easy",
    questionText: "Người nói trong đoạn thoại giới thiệu nghề nghiệp gì?",
    audioText: "你好！我是王老师，很高兴认识你。",
    options: [
      { id: "A", text: "Giáo viên" },
      { id: "B", text: "Bác sĩ" },
      { id: "C", text: "Học sinh" },
      { id: "D", text: "Tài xế" },
    ],
    correctAnswer: "A",
    explanation: "Đáp án A đúng. Người nói tự giới thiệu: '我是王老师' (Tôi là thầy/cô giáo Vương).",
    vocabularyIds: ["laoshi", "gaoxing", "renshi"],
    grammarIds: ["g_hsk1_shi"],
    tags: ["nghề nghiệp", "chào hỏi"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_lis_02",
    level: 1,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_question",
    difficulty: "easy",
    questionText: "Bây giờ là mấy giờ?",
    audioText: "现在几点？现在八点。",
    options: [
      { id: "A", text: "7 giờ" },
      { id: "B", text: "8 giờ" },
      { id: "C", text: "9 giờ" },
      { id: "D", text: "10 giờ" },
    ],
    correctAnswer: "B",
    explanation: "Đáp án B đúng. Đoạn hội thoại trả lời rõ: '现在八点' (Bây giờ là 8 giờ).",
    vocabularyIds: ["dian", "ba"],
    tags: ["thời gian", "số đếm"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_lis_03",
    level: 1,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_short",
    difficulty: "easy",
    questionText: "Cô ấy muốn uống loại đồ uống nào?",
    audioText: "你想喝什么？我想喝茶。",
    options: [
      { id: "A", text: "Nước khoáng" },
      { id: "B", text: "Cà phê" },
      { id: "C", text: "Trà" },
      { id: "D", text: "Sữa tươi" },
    ],
    correctAnswer: "C",
    explanation: "Đáp án C đúng. Cô ấy trả lời: '我想喝茶' (Tôi muốn uống trà).",
    vocabularyIds: ["he", "cha", "shenme"],
    tags: ["đồ uống", "sở thích"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_lis_04",
    level: 1,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_true_false",
    difficulty: "medium",
    questionText: "Thời tiết hôm nay như thế nào?",
    audioText: "今天天气很好，不冷。",
    options: [
      { id: "A", text: "Trời rất lạnh" },
      { id: "B", text: "Thời tiết rất tốt, không lạnh" },
      { id: "C", text: "Đang mưa to" },
      { id: "D", text: "Có tuyết rơi" },
    ],
    correctAnswer: "B",
    explanation: "Đáp án B đúng. Đoạn thoại nói: '今天天气很好，不冷' (Hôm nay thời tiết rất tốt, không lạnh).",
    vocabularyIds: ["jintian", "hao", "bu", "leng"],
    grammarIds: ["g_hsk1_bu"],
    tags: ["thời tiết", "mô tả"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_read_01",
    level: 1,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_comprehension_short",
    difficulty: "easy",
    questionText: "“这个苹果很好吃。” nghĩa là gì?",
    options: [
      { id: "A", text: "Quả táo này rất ngon." },
      { id: "B", text: "Quả táo này rất to." },
      { id: "C", text: "Quả táo này rất đắt." },
      { id: "D", text: "Tôi thích ăn táo." },
    ],
    correctAnswer: "A",
    explanation: "Đáp án A đúng. 苹果 (píngguǒ) = quả táo, 好吃 (hǎochī) = ngon.",
    vocabularyIds: ["pingguo", "haochi", "hen"],
    tags: ["hoa quả", "tính từ"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_read_02",
    level: 1,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_cloze",
    difficulty: "easy",
    questionText: "Điền từ thích hợp vào chỗ trống: “他是我的____。”",
    options: [
      { id: "A", text: "朋友", pinyin: "péngyou" },
      { id: "B", text: "很高兴", pinyin: "hěn gāoxìng" },
      { id: "C", text: "不客气", pinyin: "bù kèqi" },
      { id: "D", text: "谢谢", pinyin: "xièxie" },
    ],
    correctAnswer: "A",
    explanation: "Đáp án A đúng. Cấu trúc sở hữu '我的 + Danh từ', 朋友 (péngyou) là danh từ chỉ bạn bè phù hợp nhất.",
    vocabularyIds: ["pengyou", "de"],
    grammarIds: ["g_hsk1_de"],
    tags: ["danh từ", "điền từ"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_read_03",
    level: 1,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_match",
    difficulty: "easy",
    questionText: "Chọn từ trái nghĩa với “大” (To / Lớn):",
    options: [
      { id: "A", text: "多", pinyin: "duō" },
      { id: "B", text: "小", pinyin: "xiǎo" },
      { id: "C", text: "高", pinyin: "gāo" },
      { id: "D", text: "少", pinyin: "shǎo" },
    ],
    correctAnswer: "B",
    explanation: "Đáp án B đúng. Từ trái nghĩa với 大 (dà - to lớn) là 小 (xiǎo - nhỏ bé).",
    vocabularyIds: ["da"],
    tags: ["từ trái nghĩa"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk1_read_04",
    level: 1,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_comprehension_short",
    difficulty: "easy",
    questionText: "“我明天去中国。” có nghĩa là gì?",
    options: [
      { id: "A", text: "Ngày mai tôi đi Trung Quốc." },
      { id: "B", text: "Hôm nay tôi ở Trung Quốc." },
      { id: "C", text: "Hôm qua tôi từ Trung Quốc về." },
      { id: "D", text: "Tôi muốn học tiếng Trung." },
    ],
    correctAnswer: "A",
    explanation: "Đáp án A đúng. 明天 (míngtiān - ngày mai), 去 (qù - đi), 中国 (Zhōngguó - Trung Quốc).",
    vocabularyIds: ["mingtian", "qu"],
    tags: ["thời gian", "địa điểm"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },

  // ==========================================
  // HSK 2 QUESTIONS
  // ==========================================
  {
    id: "hsk2_lis_01",
    level: 2,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_short",
    difficulty: "easy",
    questionText: "Họ chuẩn bị chọn phương tiện gì để đi làm?",
    audioText: "外面下雨了，我们坐出租车去吧。",
    options: [
      { id: "A", text: "Đi xe buýt" },
      { id: "B", text: "Đi xe taxi vì trời mưa" },
      { id: "C", text: "Đi xe máy" },
      { id: "D", text: "Đi bộ" },
    ],
    correctAnswer: "B",
    explanation: "Đoạn nghe: 外面下雨了，我们坐出租车去吧 (Bên ngoài mưa rồi, chúng ta đi taxi nhé).",
    vocabularyIds: ["chuzuche"],
    tags: ["giao thông", "thời tiết"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk2_lis_02",
    level: 2,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_short",
    difficulty: "easy",
    questionText: "Anh ấy cảm thấy thế nào và muốn làm gì?",
    audioText: "我今天太累了，想早点睡觉。",
    options: [
      { id: "A", text: "Rất đói bụng" },
      { id: "B", text: "Rất mệt và muốn đi ngủ sớm" },
      { id: "C", text: "Vui vẻ đi chơi" },
      { id: "D", text: "Bị ốm cần đi viện" },
    ],
    correctAnswer: "B",
    explanation: "Đoạn thoại: 太累了 (quá mệt) và 想早点睡觉 (muốn đi ngủ sớm).",
    tags: ["cảm xúc", "sinh hoạt"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk2_lis_03",
    level: 2,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_question",
    difficulty: "easy",
    questionText: "Quyển sách này có giá bao nhiêu tiền?",
    audioText: "这本书五十块钱，不算贵。",
    options: [
      { id: "A", text: "15 tệ" },
      { id: "B", text: "50 tệ" },
      { id: "C", text: "100 tệ" },
      { id: "D", text: "5 tệ" },
    ],
    correctAnswer: "B",
    explanation: "Đoạn thoại: 这本书五十块钱 (Quyển sách này 50 tệ).",
    vocabularyIds: ["shu", "kuai"],
    tags: ["mua sắm", "giá cả"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk2_read_01",
    level: 2,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_comprehension_short",
    difficulty: "medium",
    questionText: "“他比我高，也比我大两岁。” có nghĩa là gì?",
    options: [
      { id: "A", text: "Anh ấy cao hơn tôi và lớn hơn tôi 2 tuổi." },
      { id: "B", text: "Tôi cao hơn anh ấy 2 cm." },
      { id: "C", text: "Anh ấy thấp hơn tôi 2 tuổi." },
      { id: "D", text: "Chúng tôi bằng tuổi nhau." },
    ],
    correctAnswer: "A",
    explanation: "Cấu trúc so sánh 比: 他比我高 (Anh ấy cao hơn tôi), 比我大两岁 (lớn hơn tôi 2 tuổi).",
    grammarIds: ["g_hsk2_bi"],
    tags: ["câu so sánh", "tuổi tác"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk2_read_02",
    level: 2,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_sentence_logic",
    difficulty: "medium",
    questionText: "Nối vế câu logic: “虽然这件衣服很贵，____。”",
    options: [
      { id: "A", text: "但是我很喜欢。" },
      { id: "B", text: "所以要睡觉。" },
      { id: "C", text: "因为下雨。" },
      { id: "D", text: "很高兴。" },
    ],
    correctAnswer: "A",
    explanation: "Cặp liên từ nhượng bộ: 虽然……但是…… (Tuy... nhưng...).",
    grammarIds: ["g_hsk2_suiran_danshi"],
    tags: ["liên từ", "logic"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk2_read_03",
    level: 2,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_cloze",
    difficulty: "medium",
    questionText: "Điền từ thích hợp: “因为身体不好，所以他今天没来____。”",
    options: [
      { id: "A", text: "上班" },
      { id: "B", text: "睡觉" },
      { id: "C", text: "跳舞" },
      { id: "D", text: "看电影" },
    ],
    correctAnswer: "A",
    explanation: "Ngữ cảnh: Vì sức khỏe không tốt nên hôm nay không đi làm (上班).",
    grammarIds: ["g_hsk2_yinwei_suoyi"],
    tags: ["nhân quả", "công việc"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },

  // ==========================================
  // HSK 3 QUESTIONS
  // ==========================================
  {
    id: "hsk3_lis_01",
    level: 3,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_question",
    difficulty: "medium",
    questionText: "Bác sĩ khuyên người bệnh nên làm gì để khỏe mạnh?",
    audioText: "医生说你需要多运动，少吃甜食，这样身体才会好。",
    options: [
      { id: "A", text: "Nên tập thể dục nhiều hơn và ăn ít đồ ngọt" },
      { id: "B", text: "Nên đi du lịch Bắc Kinh nghỉ dưỡng" },
      { id: "C", text: "Nên uống thêm nhiều cà phê mỗi sáng" },
      { id: "D", text: "Nên ngủ 12 tiếng mỗi ngày" },
    ],
    correctAnswer: "A",
    explanation: "Đoạn thoại: 多运动 (vận động nhiều hơn), 少吃甜食 (ăn ít đồ ngọt).",
    tags: ["sức khỏe", "bác sĩ"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk3_lis_02",
    level: 3,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_short",
    difficulty: "medium",
    questionText: "Thời gian và địa điểm gặp mặt của họ là khi nào?",
    audioText: "我们明天下午三点在图书馆门前见面，好吗？",
    options: [
      { id: "A", text: "Chiều mai 3 giờ tại trước cửa thư viện" },
      { id: "B", text: "Sáng mai 8 giờ tại quán ăn gần trường" },
      { id: "C", text: "Chiều nay 4 giờ tại công ty" },
      { id: "D", text: "Tối nay 7 giờ tại nhà riêng" },
    ],
    correctAnswer: "A",
    explanation: "Đoạn thoại: 明天下午三点 (Chiều mai 3 giờ), 图书馆门前 (trước cửa thư viện).",
    tags: ["hẹn gặp", "thời gian"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk3_read_01",
    level: 3,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_comprehension_short",
    difficulty: "medium",
    passage: "学汉语虽然不容易，但只要每天坚持练习，就一定能说得越来越流利。",
    questionText: "Bí quyết để nói tiếng Trung ngày càng lưu loát là gì?",
    options: [
      { id: "A", text: "Mỗi ngày kiên trì luyện tập" },
      { id: "B", text: "Chỉ cần học trong một tuần" },
      { id: "C", text: "Không cần đọc sách giáo khoa" },
      { id: "D", text: "Chỉ nghe nhạc không cần nói" },
    ],
    correctAnswer: "A",
    explanation: "Đoạn văn khẳng định: 只要每天坚持练习，就一定能说得越来越流利.",
    tags: ["đọc hiểu", "học tập"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk3_read_02",
    level: 3,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_cloze",
    difficulty: "medium",
    questionText: "Điền từ thích hợp: “这个决定对我来说非常____。”",
    options: [
      { id: "A", text: "重要" },
      { id: "B", text: "方便" },
      { id: "C", text: "客气" },
      { id: "D", text: "热情" },
    ],
    correctAnswer: "A",
    explanation: "重要 (zhòngyào - quan trọng) kết hợp chuẩn xác nhất với cấu trúc 对……来说 (đối với... mà nói).",
    tags: ["tính từ", "cấu trúc"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk3_write_01",
    level: 3,
    syllabusVersion: "2.0",
    section: "writing",
    questionType: "writing_reorder",
    difficulty: "medium",
    questionText: "Sắp xếp các từ sau thành câu đúng:",
    wordsToArrange: ["今天", "天气", "怎么样"],
    options: [
      { id: "A", text: "今天天气怎么样？" },
      { id: "B", text: "怎么样今天天气？" },
      { id: "C", text: "天气怎么样今天？" },
      { id: "D", text: "今天怎么样天气？" },
    ],
    correctAnswer: "A",
    explanation: "Cấu trúc câu hỏi thời tiết: Thời gian (今天) + Chủ ngữ (天气) + Đại từ nghi vấn (怎么样)？",
    tags: ["sắp xếp câu", "thời tiết"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk3_write_02",
    level: 3,
    syllabusVersion: "2.0",
    section: "writing",
    questionType: "writing_reorder",
    difficulty: "medium",
    questionText: "Sắp xếp các từ thành câu diễn đạt nguyện vọng:",
    wordsToArrange: ["我", "想", "去", "北京", "旅游"],
    options: [
      { id: "A", text: "我想去北京旅游。" },
      { id: "B", text: "去北京我想旅游。" },
      { id: "C", text: "北京我想去旅游。" },
      { id: "D", text: "旅游我想去北京。" },
    ],
    correctAnswer: "A",
    explanation: "Cấu trúc câu liên động từ: Chủ ngữ (我) + Trợ động từ (想) + Động từ 1 (去北京) + Động từ 2 (旅游).",
    tags: ["câu liên động", "du lịch"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },

  // ==========================================
  // HSK 4 QUESTIONS
  // ==========================================
  {
    id: "hsk4_lis_01",
    level: 4,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_dialogue_short",
    difficulty: "medium",
    questionText: "Lý do người nam xin phép nghỉ làm hôm nay là gì?",
    audioText: "经理，我今天发烧了，想请假去医院看医生。",
    options: [
      { id: "A", text: "Bị sốt và cần đến bệnh viện khám" },
      { id: "B", text: "Đi du lịch cùng gia đình" },
      { id: "C", text: "Chuyển sang công ty mới" },
      { id: "D", text: "Trời mưa không có xe đi làm" },
    ],
    correctAnswer: "A",
    explanation: "Đoạn thoại rõ ràng: 我今天发烧了，想请假去医院看医生.",
    tags: ["xin nghỉ", "sức khỏe"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk4_read_01",
    level: 4,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_order_paragraphs",
    difficulty: "hard",
    questionText: "Sắp xếp 3 vế câu thành đoạn văn chuẩn logic: (A) 总结经验 (B) 才能不断进步 (C) 只有不断",
    options: [
      { id: "A", text: "C -> A -> B" },
      { id: "B", text: "A -> B -> C" },
      { id: "C", text: "B -> C -> A" },
      { id: "D", text: "C -> B -> A" },
    ],
    correctAnswer: "A",
    explanation: "Cấu trúc điều kiện duy nhất 只有……才……: 只有 (C) 不断总结经验 (A)，才能不断进步 (B).",
    grammarIds: ["g_hsk4_zhiyou_caineng"],
    tags: ["sắp xếp vế câu", "ngữ pháp"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk4_write_01",
    level: 4,
    syllabusVersion: "2.0",
    section: "writing",
    questionType: "writing_reorder_grammar",
    difficulty: "hard",
    questionText: "Sắp xếp các từ sau thành câu chữ 把 chuẩn ngữ pháp:",
    wordsToArrange: ["请", "把", "门", "关上"],
    options: [
      { id: "A", text: "请把门关上。" },
      { id: "B", text: "把请关上门。" },
      { id: "C", text: "门把关上请。" },
      { id: "D", text: "关上门把请。" },
    ],
    correctAnswer: "A",
    explanation: "Cấu trúc câu chữ 把: Chủ ngữ + 把 + Tân ngữ chịu tác động (门) + Động từ kết quả (关上).",
    grammarIds: ["g_hsk3_ba"],
    tags: ["câu chữ 把", "HSK 4"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },

  // ==========================================
  // HSK 5 QUESTIONS
  // ==========================================
  {
    id: "hsk5_lis_01",
    level: 5,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_passage_speech",
    difficulty: "hard",
    questionText: "Theo diễn giả, cốt lõi năng lực cạnh tranh của doanh nghiệp nằm ở đâu?",
    audioText: "企业的核心竞争力在于创新。只有不断研发新产品，提升服务质量，才能在激烈的市场竞争中立于不败之地。",
    options: [
      { id: "A", text: "Đổi mới sáng tạo và nâng cao chất lượng dịch vụ" },
      { id: "B", text: "Cắt giảm tối đa chi phí nhân sự" },
      { id: "C", text: "Mở rộng diện tích nhà xưởng ngay lập tức" },
      { id: "D", text: "Tăng giá bán sản phẩm để tăng lợi nhuận" },
    ],
    correctAnswer: "A",
    explanation: "Đoạn thoại: 核心竞争力在于创新... 提升服务质量.",
    tags: ["kinh tế", "doanh nghiệp"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk5_read_01",
    level: 5,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_passage_cloze",
    difficulty: "hard",
    questionText: "Điền từ kết hợp chuẩn xác: “积极的态度能够帮助我们____困难。”",
    options: [
      { id: "A", text: "克服" },
      { id: "B", text: "放弃" },
      { id: "C", text: "减少" },
      { id: "D", text: "批评" },
    ],
    correctAnswer: "A",
    explanation: "Cụm kết hợp từ cố định: 克服困难 (kèfú kùnnan) = khắc phục / vượt qua khó khăn.",
    tags: ["kết hợp từ", "cao cấp"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk5_write_01",
    level: 5,
    syllabusVersion: "2.0",
    section: "writing",
    questionType: "writing_reorder_complex",
    difficulty: "hard",
    questionText: "Sắp xếp cụm từ thành câu phức chuẩn HSK 5:",
    wordsToArrange: ["良好的", "沟通", "是", "解决问题的", "关键"],
    options: [
      { id: "A", text: "良好的沟通是解决问题的关键。" },
      { id: "B", text: "关键是解决问题的良好的沟通。" },
      { id: "C", text: "解决问题的关键是沟通良好的。" },
      { id: "D", text: "沟通是良好的关键解决问题的。" },
    ],
    correctAnswer: "A",
    explanation: "Cấu trúc: 良好的沟通 (Sự giao tiếp tốt) + 是 (là) + 解决问题的关键 (chìa khóa giải quyết vấn đề).",
    tags: ["câu phức", "HSK 5"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },

  // ==========================================
  // HSK 6 QUESTIONS
  // ==========================================
  {
    id: "hsk6_read_01",
    level: 6,
    syllabusVersion: "2.0",
    section: "reading",
    questionType: "reading_error_detection",
    difficulty: "hard",
    questionText: "Chọn câu chứa lỗi sai ngữ pháp (病句):",
    options: [
      { id: "A", text: "通过这次活动，使我认识到了团队合作的重要性。" },
      { id: "B", text: "只要我们坚持不懈，就一定能取得成功。" },
      { id: "C", text: "图书馆里静悄悄的，连针掉在地上都能听见。" },
      { id: "D", text: "他不仅很聪明，而且非常勤奋。" },
    ],
    correctAnswer: "A",
    explanation: "Đáp án A sai lỗi thiếu chủ ngữ do dùng cả '通过……' (qua...) và '使……' (khiến...) cùng lúc làm mất chủ ngữ thực.",
    grammarIds: ["g_hsk6_bingju_zhuyu"],
    tags: ["bệnh cú", "sửa lỗi", "HSK 6"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk6_lis_01",
    level: 6,
    syllabusVersion: "2.0",
    section: "listening",
    questionType: "listening_philosophy_story",
    difficulty: "hard",
    questionText: "Thông điệp chính của câu chuyện triết học là gì?",
    audioText: "水滴石穿，不是因为水的力量强大，而是因为持之以恒的毅力。在人生的道路上，恒心往往比一时爆发的激情更加重要。",
    options: [
      { id: "A", text: "Sự kiên trì và hằng tâm quan trọng hơn sự bồng bột bốc đồng" },
      { id: "B", text: "Sức mạnh của nước là vô địch trong thiên nhiên" },
      { id: "C", text: "Con người cần mua nhiều hòn đá để xây nhà" },
      { id: "D", text: "Thất bại là do không đủ tiền bạc" },
    ],
    correctAnswer: "A",
    explanation: "Đoạn thoại: 恒心往往比一时爆发的激情更加重要 (Hằng tâm thường quan trọng hơn đam mê bộc phát nhất thời).",
    tags: ["triết học", "thành ngữ"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
  {
    id: "hsk6_write_01",
    level: 6,
    syllabusVersion: "2.0",
    section: "writing",
    questionType: "writing_summary_reorder",
    difficulty: "hard",
    questionText: "Sắp xếp cụm từ thành thành ngữ kinh điển HSK 6:",
    wordsToArrange: ["千里之行", "始于", "足下"],
    options: [
      { id: "A", text: "千里之行，始于足下。" },
      { id: "B", text: "始于足下，千里之行。" },
      { id: "C", text: "足下始于，千里之行。" },
      { id: "D", text: "千里足下，始于之行。" },
    ],
    correctAnswer: "A",
    explanation: "Thành ngữ HSK 6: 千里之行，始于足下 (Hành trình vạn dặm bắt đầu từ một bước chân).",
    tags: ["thành ngữ", "tục ngữ", "HSK 6"],
    qualityScore: 1.0,
    status: "approved",
    source: "official",
  },
];

export function getQuestionsByLevel(level: number): HSKQuestion[] {
  return QUESTION_BANK.filter((q) => q.level === level);
}
